"""Generate the requirement traceability matrix and enforce its gates.

Forward (requirement → tests) proves coverage; backward (test → requirement) catches
markers pointing at ids that no longer exist. `Implemented` is therefore *computed* here,
never claimed in a feature file (11-engineering-standards.md § requirement traceability).

The matrix is a CI artefact and is deliberately **not** committed: a generated file in
the repository is a staleness bug waiting to happen.

    python -m tools.traceability --report fr-report.json --output traceability-matrix.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from tools.specdocs import (
    DEFAULT_METHOD,
    Feature,
    Finding,
    Invariant,
    load_features,
    load_invariants,
)

UNCOVERED = "—"

#: Requirement text is written for its feature file, so its relative links resolve from
#: `features/`. The matrix lives elsewhere and is read as a table — keep the words, drop
#: the link syntax rather than emitting links that point nowhere.
_MARKDOWN_LINK = re.compile(r"\[([^\]]+)\]\([^)]*\)")


def plain(text: str) -> str:
    return " ".join(_MARKDOWN_LINK.sub(r"\1", text).split())


def status_token(status: str) -> str:
    """`Deferred (design sketch — …)` reads as `Deferred` in a table cell."""
    return re.split(r"[(\u2014]", status, maxsplit=1)[0].strip()


@dataclass(frozen=True)
class Coverage:
    nodeid: str
    methods: tuple[str, ...]
    outcome: str


@dataclass(frozen=True)
class Row:
    id: str
    requirement: str
    owner: str
    method: str
    covering: tuple[Coverage, ...]
    note: str

    @property
    def verified(self) -> bool:
        """Covered by at least one *passing* test using the declared method."""
        return any(
            coverage.outcome == "passed" and self.method in coverage.methods
            for coverage in self.covering
        )

    @property
    def result(self) -> str:
        if not self.covering:
            return "not covered"
        outcomes = {coverage.outcome for coverage in self.covering}
        for outcome in ("failed", "error", "not run", "skipped"):
            if outcome in outcomes:
                return outcome
        return "passed"


def load_coverage(path: Path) -> dict[str, list[Coverage]]:
    """Invert the plugin's test → requirements report into requirement → tests."""
    document = json.loads(path.read_text(encoding="utf-8"))
    coverage: dict[str, list[Coverage]] = defaultdict(list)
    for nodeid, entry in document.get("tests", {}).items():
        record = Coverage(nodeid, tuple(entry.get("methods", [])), str(entry.get("outcome", "")))
        for requirement_id in entry.get("requirements", []):
            coverage[str(requirement_id)].append(record)
    return dict(coverage)


def build_rows(
    features: list[Feature],
    invariants: list[Invariant],
    coverage: dict[str, list[Coverage]],
) -> list[Row]:
    rows: list[Row] = []

    for feature in features:
        for requirement in feature.requirements:
            rows.append(
                Row(
                    id=requirement.id,
                    requirement=plain(requirement.text) or "(tombstone)",
                    owner=f"{feature.id} ({status_token(feature.status)})",
                    method=requirement.method,
                    covering=tuple(coverage.get(requirement.id, ())),
                    note="tombstone" if requirement.tombstoned else "",
                )
            )

    for invariant in invariants:
        rows.append(
            Row(
                id=invariant.id,
                requirement=plain(invariant.text),
                owner="02-domain-model",
                method=DEFAULT_METHOD,
                covering=tuple(coverage.get(invariant.id, ())),
                note="",
            )
        )

    return rows


def render_markdown(rows: list[Row]) -> str:
    verified = sum(1 for row in rows if row.verified)
    live = [row for row in rows if not row.note]

    lines = [
        "# Requirement traceability matrix",
        "",
        "Generated by `make matrix`; never committed. `Implemented` is computed from this,",
        "never claimed in a feature file.",
        "",
        f"**{verified} of {len(live)}** live requirements are verified by their declared method.",
        "",
        "| Id | Requirement | Owner | Method | Covering tests | Result | Note |",
        "|---|---|---|---|---|---|---|",
    ]

    for row in rows:
        tests = "<br>".join(coverage.nodeid for coverage in row.covering) or UNCOVERED
        requirement = row.requirement.replace("|", "\\|")
        if len(requirement) > 160:
            requirement = requirement[:159].rstrip() + "…"
        lines.append(
            f"| `{row.id}` | {requirement} | {row.owner} | {row.method} | "
            f"{tests} | {row.result} | {row.note} |"
        )

    return "\n".join(lines) + "\n"


def gate(
    features: list[Feature],
    rows: list[Row],
    coverage: dict[str, list[Coverage]],
) -> list[Finding]:
    """Hard gates fail the pipeline; soft gates report and let it pass."""
    findings: list[Finding] = []
    by_id = {row.id: row for row in rows}
    tombstoned = {row.id for row in rows if row.note == "tombstone"}

    # Backward: a marker pointing at nothing means a test guards a requirement that no
    # longer exists — or never did.
    for requirement_id, records in sorted(coverage.items()):
        for record in records:
            if requirement_id not in by_id:
                findings.append(
                    Finding("error", record.nodeid, f"marks {requirement_id}, which does not exist")
                )
            elif requirement_id in tombstoned:
                findings.append(
                    Finding("error", record.nodeid, f"marks {requirement_id}, which is a tombstone")
                )

    # Forward: a feature may only claim `Implemented` when every live requirement is
    # verified by its declared method.
    for feature in features:
        if not feature.is_implemented:
            continue
        for requirement in feature.requirements:
            if requirement.tombstoned:
                continue
            row = by_id.get(requirement.id)
            if row is None or not row.verified:
                findings.append(
                    Finding(
                        "error",
                        feature.path.name,
                        f"claims Implemented but {requirement.id} has no passing "
                        f"{requirement.method} verification",
                    )
                )

    # Soft: a declared method whose suite does not exist yet.
    wired = {
        method for records in coverage.values() for record in records for method in record.methods
    }
    for method in sorted({row.method for row in rows if not row.note} - wired - {DEFAULT_METHOD}):
        waiting = [row.id for row in rows if row.method == method and not row.note]
        findings.append(
            Finding(
                "warning",
                "matrix",
                f"{len(waiting)} requirement(s) declare '{method}', whose suite is not wired "
                f"up yet (e.g. {', '.join(waiting[:3])})",
            )
        )

    return findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, required=True, help="JSON written by --fr-report")
    parser.add_argument("--output", type=Path, help="write the matrix here")
    args = parser.parse_args(argv)

    if not args.report.exists():
        print(
            f"{args.report} does not exist — run the suite with --fr-report first",
            file=sys.stderr,
        )
        return 1

    features = load_features()
    invariants = load_invariants()
    coverage = load_coverage(args.report)

    rows = build_rows(features, invariants, coverage)
    findings = gate(features, rows, coverage)

    if args.output is not None:
        args.output.write_text(render_markdown(rows), encoding="utf-8")
        print(f"wrote {args.output}")

    for finding in findings:
        print(finding.render(), file=sys.stderr if finding.level == "error" else sys.stdout)

    errors = [finding for finding in findings if finding.level == "error"]
    live = [row for row in rows if not row.note]
    verified = sum(1 for row in live if row.verified)
    print(f"\n{verified}/{len(live)} live requirements verified; {len(errors)} gate failure(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
