"""The derived store: where generated bytes live.

Laid out as [09 § storage](../../../specs/09-previews.md#storage) fixes it — one directory per
*source* content hash, sharded:

    derived/{hh}/{content-hash}/thumb-256.webp
    derived/{hh}/{content-hash}/page-0001.webp

Keying on the source's hash rather than the asset's own is what makes duplicate files share one
set of assets for free: two copies of a photo hash identically, so both point at the same
directory, and reusing an extraction result costs nothing because the bytes are already where the
second file would have put them.

**The core owns the directory; the extractor names the file.** A plugin producing a turntable
render should not need a core change to call it `turntable.glb`, and the core has no opinion worth
having about that name — only about where it may go, and that it is a name rather than a path.
Both halves are enforced here.

Assets arrive in two phases (05 § dispatch): staged by their own digest and hash-verified on
receipt, then moved into place inside the transaction that records them. Bytes before rows, in
that order, exactly like every other write in this system (02 § invariants #8) — and staging
debris is collected by the janitor, which already sweeps this area.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from uuid import UUID

from store_everything import filestore

#: One shard level of two characters, as spec 09 draws it. Enough to keep any single directory
#: to a few thousand entries at this product's scale, and short enough to read aloud.
_SHARD = 2

STAGING_DIRECTORY = "staging"

#: What an extractor may call its output. Deliberately strict: this becomes a filename in an
#: app-owned directory, so anything that could be a path, a hidden file, or a shell surprise is
#: refused rather than sanitised — silently rewriting a name would make the row and the disk
#: disagree about what the asset is called.
_NAME = re.compile(r"^[a-z0-9][a-z0-9._-]{0,63}$")
_FORBIDDEN = ("..",)

MAX_NAME_LENGTH = 64


class InvalidAssetNameError(ValueError):
    """The name an extractor chose for an asset cannot be stored."""


def validate_name(name: str) -> str:
    """The asset's filename, or a refusal naming the rule it broke."""
    if not _NAME.match(name):
        raise InvalidAssetNameError(
            f"{name!r} is not a usable asset name: lower-case letters, digits, dot, dash and "
            f"underscore, starting with a letter or digit, at most {MAX_NAME_LENGTH} characters"
        )
    if any(part in name for part in _FORBIDDEN):
        raise InvalidAssetNameError(f"{name!r} may not contain '..'")
    return name


@dataclass(frozen=True, slots=True)
class DerivedStore:
    """The derived area of the app-owned storage."""

    root: Path

    @property
    def staging_root(self) -> Path:
        return self.root / STAGING_DIRECTORY

    def directory_for(self, source_hash: str) -> Path:
        """Everything derived from one set of bytes, in one place — so a purge is one removal."""
        _validate_hash(source_hash)
        return self.root / source_hash[:_SHARD] / source_hash

    def path_for(self, source_hash: str, name: str) -> Path:
        return self.directory_for(source_hash) / validate_name(name)

    def contains(self, source_hash: str, name: str) -> bool:
        return self.path_for(source_hash, name).is_file()

    # ------------------------------------------------------------------ two-phase writes

    def staging_path(self, *, operation_id: UUID, digest: str) -> Path:
        """Where an uploaded asset waits until the result that references it is applied.

        Named by the operation *and* the digest: an extractor stages several assets for one job,
        and the janitor has to be able to tell whose debris it is looking at (12 § debris).
        """
        _validate_hash(digest)
        return filestore.staging_path(self.staging_root, operation_id, part=digest)

    def stage(self, *, operation_id: UUID, digest: str, data: bytes) -> Path:
        """Write one asset to staging, verifying it is what it claims to be.

        The digest is the caller's claim and this is where it stops being a claim: a mismatch
        means the bytes are not the ones the result envelope will reference, and storing them
        would put an asset under a hash that does not describe it.
        """
        actual = filestore.digest_of(data)
        if actual != digest:
            raise ValueError(f"the staged bytes hash to {actual}, not to {digest}")
        staged = self.staging_path(operation_id=operation_id, digest=digest)
        filestore.ensure_directory(staged.parent)
        filestore.write_atomically(staged, data, staging=staged.with_suffix(".partial"))
        return staged

    def commit(self, staged: Path, *, source_hash: str, name: str) -> Path:
        """Move a staged asset into place. Idempotent: a re-run finds it already there.

        Both paths are under the app-data root, so this is a rename rather than a copy — which
        is what makes it atomic, and why the staging area lives here rather than anywhere more
        convenient.
        """
        destination = self.path_for(source_hash, name)
        if destination.is_file() and not staged.exists():
            # The previous attempt got this far. Nothing to move and nothing to worry about.
            return destination
        filestore.ensure_directory(destination.parent)
        filestore.commit_staged(staged, destination)
        return destination

    def remove(self, source_hash: str, name: str) -> bool:
        return filestore.remove(self.path_for(source_hash, name))

    def remove_all(self, source_hash: str) -> int:
        """Every asset derived from these bytes. Returns how many files went.

        The whole point of the layout: reprocessing and purging both need "forget what was
        derived from this", and here that is one directory rather than a query.
        """
        directory = self.directory_for(source_hash)
        if not directory.is_dir():
            return 0
        removed = sum(1 for entry in directory.iterdir() if filestore.remove(entry))
        directory.rmdir()
        filestore.fsync_directory(directory.parent)
        return removed


def _validate_hash(digest: str) -> None:
    if len(digest) != 64 or not all(character in "0123456789abcdef" for character in digest):
        raise ValueError(f"{digest!r} is not a sha256 hex digest")


__all__ = [
    "MAX_NAME_LENGTH",
    "STAGING_DIRECTORY",
    "DerivedStore",
    "InvalidAssetNameError",
    "validate_name",
]
