"""Table definitions and the single SQLAlchemy metadata they register on.

There are no ORM model classes by design (ADR-0012): tables are declared here as Core
`Table` objects, and rows map to Pydantic models at the API boundary (`schemas.py`).

Fixing the naming convention *before* the first table exists is deliberate: constraint
and index names become part of migrations the moment a table is created, and renaming
them later is a migration of its own.

Migrations are hand-written rather than autogenerated, so this file and the migration
history could drift. `tests/test_schema_matches_metadata.py` closes that gap by comparing
this metadata against a freshly migrated database.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    ForeignKeyConstraint,
    Identity,
    Index,
    Integer,
    MetaData,
    PrimaryKeyConstraint,
    SmallInteger,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import INET, JSONB, UUID

from store_everything.names import MAX_NAME_BYTES, MAX_PATH_BYTES

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)

#: Instance-level roles (07-identity-permissions-sharing.md Â§ users).
USER_ROLES = ("admin", "member")

#: Personal-access-token scopes. `read` is least privilege for an agent or a read-only
#: integration; `full` acts as its user. Finer scopes are additive later.
TOKEN_SCOPES = ("read", "full")

#: Who acted (ADR-0007). `system` covers scheduled and startup work with no human behind it.
ACTOR_TYPES = ("user", "extractor", "system")


def _created_at() -> Column[datetime]:
    return Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now())


def one_of(column: str, allowed: tuple[str, ...]) -> str:
    """SQL for "this column holds one of these values".

    Written by hand rather than interpolating a Python tuple: a single-element tuple
    renders as `('x',)`, which is a syntax error, and the migration has to carry the
    identical text.
    """
    values = ", ".join(f"'{value}'" for value in allowed)
    return f"{column} IN ({values})"


app_user = Table(
    "app_user",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    # Stored lower-cased so "Alice@example.com" and "alice@example.com" are one account;
    # the check constraint makes that structural instead of a convention handlers remember.
    Column("email", Text, nullable=False),
    Column("display_name", Text, nullable=False),
    Column("password_hash", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("is_active", Boolean, nullable=False, server_default=text("true")),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("email"),
    CheckConstraint("email = lower(email)", name="email_lowercase"),
    CheckConstraint("length(email) BETWEEN 3 AND 320", name="email_length"),
    CheckConstraint("length(display_name) BETWEEN 1 AND 200", name="display_name_length"),
    CheckConstraint(one_of("role", USER_ROLES), name="role_known"),
)
"""Named `app_user` because `user` is a reserved word in PostgreSQL â quoting it forever
in hand-written SQL (ADR-0012) is a papercut with no upside."""


user_session = Table(
    "user_session",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # Only the SHA-256 of the token: a database dump can therefore not be replayed as a
    # set of live sessions (07 Â§ tokens & credentials).
    Column("token_hash", Text, nullable=False),
    Column("user_agent", Text, nullable=True),
    _created_at(),
    Column("last_used_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # Rolling idle expiry: extended on use, so an active session survives and an abandoned
    # one lapses on its own.
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("token_hash"),
    Index("ix_user_session_user_id_created_at", "user_id", "created_at"),
)


access_token = Table(
    "access_token",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("token_hash", Text, nullable=False),
    Column("scope", Text, nullable=False),
    _created_at(),
    Column("last_used_at", DateTime(timezone=True), nullable=True),
    Column("expires_at", DateTime(timezone=True), nullable=True),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("token_hash"),
    # A name is how its owner recognizes a token in a list, so it has to be unambiguous.
    UniqueConstraint("user_id", "name"),
    CheckConstraint("length(name) BETWEEN 1 AND 100", name="name_length"),
    CheckConstraint(one_of("scope", TOKEN_SCOPES), name="scope_known"),
)


event = Table(
    "event",
    metadata,
    # A gapless-looking integer, not a UUID: the `/events` feed (phase 5) is a cursor over
    # this column. Note for that phase â identity values are assigned before commit, so
    # ids can become visible out of order under concurrency; a cursor feed needs a
    # commit-order-safe watermark rather than `id > $cursor` alone.
    Column("id", BigInteger, Identity(always=True), primary_key=True),
    Column("occurred_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("actor_type", Text, nullable=False),
    # RESTRICT, not CASCADE or SET NULL: the audit trail outlives everything else
    # (F-011/FR-2), so removing a user is a decision a later phase has to make
    # deliberately rather than a side effect of a foreign key.
    Column(
        "actor_user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=True,
    ),
    Column("action", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("resource_id", UUID(as_uuid=True), nullable=True),
    # Self-contained by design (F-011/FR-9): names and paths as they were at action time,
    # so history stays readable after the resource is purged.
    Column("details", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("request_id", Text, nullable=True),
    Column("client_ip", INET, nullable=True),
    CheckConstraint(one_of("actor_type", ACTOR_TYPES), name="actor_type_known"),
    CheckConstraint(
        "actor_type <> 'user' OR actor_user_id IS NOT NULL",
        name="user_actor_identified",
    ),
    Index("ix_event_occurred_at_id", "occurred_at", "id"),
    Index("ix_event_resource_type_resource_id_id", "resource_type", "resource_id", "id"),
    Index("ix_event_actor_user_id_id", "actor_user_id", "id"),
    # Serves the credential-abuse queries, which count recent events of one action
    # (07 Â§ abuse protection).
    Index("ix_event_action_occurred_at", "action", "occurred_at"),
)
"""The append-only event log (ADR-0007). Writes ride the transaction of the change they
describe; `UPDATE` is refused by a database trigger, so immutability does not depend on
every future code path remembering it."""


#: The operation state machine (12-reliability.md Â§ operation records). `queued` doubles as
#: "waiting for a retry" â a retryable failure returns to it with a later `next_due_at` â so
#: the only non-terminal states are `queued` and `running`.
OPERATION_STATES = (
    "queued",
    "running",
    "succeeded",
    "failed",
    "dead_letter",
    "cancelled",
    "superseded",
)

#: Nothing claims these again, and their idempotency key becomes free for reuse.
TERMINAL_OPERATION_STATES = ("succeeded", "failed", "dead_letter", "cancelled", "superseded")

#: Priority classes from 04-ingestion-pipeline.md Â§ prioritization: 0 = interactive,
#: 1 = presence, 2 = searchability, 3 = heavy derived, 4 = reprocessing. Lower runs first.
MIN_PRIORITY, MAX_PRIORITY = 0, 4


operation = Table(
    "operation",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("kind", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'queued'")),
    Column("priority", SmallInteger, nullable=False, server_default=text("2")),
    # Counted on *claim*, not on failure: a job that OOM-kills its worker never reports an
    # error, and counting here is what dead-letters it anyway (12 Â§ leases & fencing).
    Column("attempt", Integer, nullable=False, server_default=text("0")),
    Column("max_attempts", Integer, nullable=False),
    # The durable schedule. Retry backoff, periodic work and "run now" are all this column;
    # in-memory timers are forbidden (ADR-0010 rule 1).
    Column("next_due_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("leased_by", Text, nullable=True),
    Column("lease_expires_at", DateTime(timezone=True), nullable=True),
    # The cancellation channel: a worker learns of it from its heartbeat response rather
    # than from a signal, so cancellation survives a restart like everything else.
    Column("cancel_requested", Boolean, nullable=False, server_default=text("false")),
    Column("idempotency_key", Text, nullable=True),
    Column("payload", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("result", JSONB, nullable=True),
    Column("error", Text, nullable=True),
    # What the operation is about, so per-file and per-workspace status stays answerable
    # (04 Â§ status & observability) without one table per operation kind.
    Column("subject_type", Text, nullable=True),
    Column("subject_id", UUID(as_uuid=True), nullable=True),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    CheckConstraint(one_of("state", OPERATION_STATES), name="state_known"),
    CheckConstraint(
        f"priority BETWEEN {MIN_PRIORITY} AND {MAX_PRIORITY}", name="priority_in_range"
    ),
    CheckConstraint("max_attempts > 0", name="max_attempts_positive"),
    CheckConstraint("attempt >= 0", name="attempt_not_negative"),
    CheckConstraint("lease_expires_at IS NULL OR leased_by IS NOT NULL", name="lease_has_an_owner"),
    # The claim query reads only claimable rows, and a 10 TB import leaves millions of
    # terminal ones behind (12 Â§ queue hygiene) â so the index covers the live set only.
    Index(
        "ix_operation_claimable",
        "priority",
        "next_due_at",
        postgresql_where=text("state IN ('queued', 'running')"),
    ),
    # At most one *queued* operation per key, which is what makes re-detecting pending work
    # converge instead of duplicating it. Deliberately not extended to `running`: a periodic
    # operation queues its own successor while it is still executing, and a key held by the
    # in-flight run would make that impossible. Convergence with running work is a question
    # about work identity rather than about the queue, so `operations.enqueue` answers it.
    Index(
        "uq_operation_idempotency_key",
        "idempotency_key",
        unique=True,
        postgresql_where=text("idempotency_key IS NOT NULL AND state = 'queued'"),
    ),
    Index("ix_operation_kind_state", "kind", "state"),
    Index("ix_operation_subject_type_subject_id", "subject_type", "subject_id"),
)
"""One table for every effectful operation (ADR-0013). A feature that invents its own job
handling is a review-blocker, exactly as ad-hoc file IO is."""


#: Where a workspace's files come from (03 Â§ workspace sources). A column rather than an
#: assumption because `external` (mirrored Google Drive and friends â Q16) is a later
#: source type, not a later redesign.
WORKSPACE_SOURCES = ("local",)

#: Who chose the root directory (ADR-0018): `managed` is ours to shape under `SE_DATA_ROOT`,
#: `adopted` is the user's own directory indexed in place with nothing moved or copied.
WORKSPACE_PLACEMENTS = ("managed", "adopted")

#: A workspace row exists before its directory does â creation records the intent and the
#: `workspace.provision` operation makes it true (ADR-0010). `active` means the root, the
#: control directory and the root folder are all there.
WORKSPACE_STATES = ("provisioning", "active")

#: Whether a worker is listening for filesystem events on this root (ADR-0019's watcher).
#: `unavailable` is not an error state â the kernel's watch limit, a permission, or a mount that
#: went away â it means this workspace has only the scheduled pass, which is the one that
#: cannot be missed anyway.
WORKSPACE_WATCH_STATES = ("unwatched", "watching", "unavailable")


workspace = Table(
    "workspace",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    # RESTRICT for the same reason as the event log's actor: a user owns files, so removing
    # one is a data-lifecycle decision (phase 4), never a foreign key's side effect.
    Column(
        "owner_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=False,
    ),
    # `name` as the user typed it, `name_key` what uniqueness and lookups compare
    # (03 Â§ names on disk). Deriving the key in Python is deliberate: case folding is a
    # Unicode operation with a policy behind it (`names.comparison_key`), not `lower()`.
    Column("name", Text, nullable=False),
    Column("name_key", Text, nullable=False),
    Column("source", Text, nullable=False, server_default=text("'local'")),
    Column("placement", Text, nullable=False),
    # Absolute and resolved (`realpath`), so containment checks compare what the kernel
    # would open rather than what a request said.
    Column("root_path", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'provisioning'")),
    # The `fs-check` verdict that admitted this root (ADR-0019). Recorded, not assumed: when
    # a guarantee later turns out not to hold, this says what was probed and what it answered.
    Column("fs_check", JSONB, nullable=False),
    Column("fs_checked_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # ADR-0019's scan schedule: the correctness backstop for external changes, hourly by
    # default and per-workspace because a photo archive and a working directory do not want
    # the same cadence.
    Column("scan_interval_minutes", Integer, nullable=False, server_default=text("60")),
    # Whether the fast path in front of that schedule is actually listening, and why not when
    # it is not (ADR-0019's watcher). Written by the worker that holds the subscription, so a
    # user asking "why did my change take an hour?" has an answer that is not a log file.
    Column("watch_state", Text, nullable=False, server_default=text("'unwatched'")),
    Column("watch_detail", Text, nullable=True),
    # The moment this workspace's rollup queue was last observed empty (F-015/FR-8). Not "when
    # the numbers were last touched": a folder nothing has changed for a week is not stale, and a
    # timestamp saying so would be noise. Per workspace because that is the unit a drain claims.
    Column(
        "aggregates_as_of",
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    ),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # One user's workspace names are unique on the comparison key, which is also what keeps
    # their managed directories from colliding â the name is a path segment.
    UniqueConstraint("owner_id", "name_key"),
    # Overlap (one root inside another) needs a query; equality is caught structurally here,
    # which is what makes the check-then-insert race harmless.
    UniqueConstraint("root_path"),
    CheckConstraint(one_of("source", WORKSPACE_SOURCES), name="source_known"),
    CheckConstraint(one_of("placement", WORKSPACE_PLACEMENTS), name="placement_known"),
    CheckConstraint(one_of("state", WORKSPACE_STATES), name="state_known"),
    CheckConstraint(one_of("watch_state", WORKSPACE_WATCH_STATES), name="watch_state_known"),
    # `octet_length`, not `length`: the policy is bytes, and a name of 255 characters can be
    # four times that on disk.
    CheckConstraint(f"octet_length(name) BETWEEN 1 AND {MAX_NAME_BYTES}", name="name_length"),
    CheckConstraint(f"octet_length(name_key) BETWEEN 1 AND {MAX_NAME_BYTES}", name="key_length"),
    CheckConstraint("root_path LIKE '/%'", name="root_path_absolute"),
    CheckConstraint("scan_interval_minutes > 0", name="scan_interval_positive"),
    CheckConstraint(f"octet_length(root_path) <= {MAX_PATH_BYTES}", name="root_path_length"),
    Index("ix_workspace_owner_id_created_at", "owner_id", "created_at"),
)
"""A top-level container of files, owned by exactly one user (02 Â§ workspace)."""


folder = Table(
    "folder",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "workspace_id",
        UUID(as_uuid=True),
        ForeignKey("workspace.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("parent_id", UUID(as_uuid=True), ForeignKey("folder.id", ondelete="CASCADE")),
    Column("name", Text, nullable=False),
    Column("name_key", Text, nullable=False),
    # Redundant with the closure table and worth it: "how deep is this" answers path
    # assembly and the depth limit without a join.
    Column("depth", Integer, nullable=False, server_default=text("0")),
    # When a scan last accounted for this directory — stamped when its **parent's** listing
    # mentioned it, the same rule that stamps a file. So a directory the scan could not read is
    # still seen (its parent listed it), and one renamed away is not, which is the whole evidence
    # for F-015/FR-7. No index: the identity pass looks folders up by id, never by this column.
    Column("last_seen_at", DateTime(timezone=True), nullable=True),
    # The filesystem this directory was on when a scan last listed it (`st_dev`). A mountpoint
    # whose mount has gone away lists as an empty directory on its *parent's* device — no error,
    # no marker, nothing to distinguish it from a directory somebody emptied — so this number is
    # the only evidence that the storage under a folder is not the storage we indexed
    # (F-001/FR-22). NULL until a scan has listed the directory once.
    Column("device_id", BigInteger, nullable=True),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # Sibling uniqueness on the comparison key (F-015/FR-6). Root rows have a NULL parent and
    # never collide here â PostgreSQL treats NULLs as distinct â which the partial index below
    # is for.
    UniqueConstraint("workspace_id", "parent_id", "name_key"),
    Index(
        "uq_folder_workspace_root",
        "workspace_id",
        unique=True,
        postgresql_where=text("parent_id IS NULL"),
    ),
    # The root folder *is* the workspace root directory, so it has no name of its own; every
    # other folder must have one. Structural, because a root that acquired a name would make
    # every derived path wrong.
    # The target of `file`'s composite foreign key. Redundant with the primary key as an
    # index, and load-bearing as a constraint: a foreign key can only reference a uniquely
    # constrained set of columns.
    UniqueConstraint("id", "workspace_id"),
    CheckConstraint("(parent_id IS NULL) = (name = '')", name="root_has_no_name"),
    CheckConstraint("(parent_id IS NULL) = (depth = 0)", name="depth_matches_parent"),
    CheckConstraint(f"octet_length(name) <= {MAX_NAME_BYTES}", name="name_length"),
    Index("ix_folder_parent_id", "parent_id"),
)
"""A directory in a workspace's tree, mirrored 1:1 from disk (F-015). Identified by its
UUID, which survives rename and move â that is what grants and tags attach to."""


folder_closure = Table(
    "folder_closure",
    metadata,
    Column(
        "ancestor_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "descendant_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("depth", Integer, nullable=False),
    # "Every ancestor of X" â the direction permission evaluation reads.
    Index("ix_folder_closure_descendant_id_depth", "descendant_id", "depth"),
    CheckConstraint("depth >= 0", name="depth_not_negative"),
    CheckConstraint("(ancestor_id = descendant_id) = (depth = 0)", name="self_row_at_depth_zero"),
)
"""Precomputed ancestry (F-015/FR-2, the ADR-0006 pattern): one indexed join answers
"everything under folder F", which is the permission filter's hottest question. Every folder
carries a depth-0 row for itself, so a subtree includes its own root without a special case."""


folder_aggregate = Table(
    "folder_aggregate",
    metadata,
    Column(
        "folder_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("total_files", BigInteger, nullable=False, server_default=text("0")),
    Column("total_bytes", BigInteger, nullable=False, server_default=text("0")),
    # When the rotating sweep last compared these numbers against ground truth. NULL sorts
    # first, so a folder that has never been checked â a new one, or one an upsert created
    # because its row was missing â is the next one checked.
    Column("verified_at", DateTime(timezone=True), nullable=True),
    # A count of files cannot be negative and neither can a sum of their sizes, so a rollup
    # that would make one negative is a bug in the arithmetic rather than a number to serve.
    # Structural on purpose: the rollup fails, retries, and dead-letters loudly, which is what
    # this system does with code that is wrong.
    CheckConstraint("total_files >= 0", name="total_files_not_negative"),
    CheckConstraint("total_bytes >= 0", name="total_bytes_not_negative"),
    Index("ix_folder_aggregate_verified_at", "verified_at"),
)
"""What a folder's whole subtree adds up to (F-015/FR-8) â recursive file count and recursive
size, over **live** files and their current version's bytes. Version history and trash are their
own categories in `/stats/storage` ([09](09-previews.md#disk-usage-visibility)) and are not here.

A table of its own rather than columns on `folder`, for two reasons: these numbers are rewritten
on every upload while the `folder` row is read by every closure join and every path assembly, and
`verified_at` is bookkeeping about the aggregate rather than about the folder.

The **direct** file count FR-8 also asks for is deliberately absent: it is one indexed count over
`file` (`uq_file_live_name`'s leading column), so it is computed at read time and is always
exact. Only the recursive pair is eventually consistent, and only it needs a stamp."""


folder_delta = Table(
    "folder_delta",
    metadata,
    # An integer rather than a UUID: an import writes one of these per file, and they are only
    # ever read as an ordered batch on the way to being deleted.
    Column("id", BigInteger, Identity(always=True), primary_key=True),
    # Which workspace's rollup owns this row. Denormalised from the folder deliberately: it is
    # what lets one drain claim one workspace's work while holding only that workspace's lock,
    # and a cross-workspace folder move re-tags the rows it moves.
    Column(
        "workspace_id",
        UUID(as_uuid=True),
        ForeignKey("workspace.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column(
        "folder_id", UUID(as_uuid=True), ForeignKey("folder.id", ondelete="CASCADE"), nullable=False
    ),
    Column("file_count", BigInteger, nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    _created_at(),
    # The drain's claim: this workspace's oldest rows first.
    Index("ix_folder_delta_workspace_id_id", "workspace_id", "id"),
    # "Is anything still queued under this folder?" â the `pending` flag every read reports,
    # driven from the closure into this index.
    Index("ix_folder_delta_folder_id", "folder_id"),
)
"""**The rollup outbox** (F-015/FR-8): one row per change, written on the same connection and in
the same transaction as the change it describes â the [events](../events.py) pattern, for
arithmetic instead of audit.

A second outbox rather than a consumer of the event log, and the reason is ordering. Addition
commutes, so this queue needs no cursor, no order and no exactly-once delivery: a batch is
`DELETE â¦ RETURNING`-ed and added to the aggregates **in one transaction**, so a crash re-applies
nothing and loses nothing. Reading the event log instead would mean holding a cursor over a table
where a transaction can commit *behind* the cursor's position, and a delta silently skipped there
is a number that stays wrong until the next drift sweep.

A row's numbers apply to `folder_id` **and to every one of its ancestors** â the drain expands
them over the closure. That is why a file move needs no common-ancestor arithmetic: -1 at the old
folder and +1 at the new one net to zero at every ancestor they share."""


#: A file's lifecycle (02 Â§ file, [F-014](../../../features/F-014-deletion-and-trash.md)).
#: Phase 1 records `trashed` only so a re-scan can capture a deletion that already happened on
#: disk; deleting *through* the app arrives with the trash surface in phase 4.
FILE_STATES = ("live", "trashed")

#: Who wrote the bytes this version describes (F-007/FR-3). `external` is what a re-scan
#: records when a file changed on disk without the app mediating it.
VERSION_ORIGINS = ("upload", "external")

#: 04 Â§ identification. Assigned by the core from the detected media type before any
#: extractor runs, which is what makes type-scoped listings work on a brand-new file.
MEDIA_CLASSES = ("image", "video", "audio", "document", "archive", "other")

#: Stored beside every hash so a future algorithm is an additive change (02 Â§ FileVersion).
DIGEST_ALGORITHMS = ("sha256",)


file = Table(
    "file",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("workspace_id", UUID(as_uuid=True), nullable=False),
    Column("folder_id", UUID(as_uuid=True), nullable=False),
    Column("name", Text, nullable=False),
    Column("name_key", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'live'")),
    # When a scan last found this file on disk. One column instead of a per-run table of
    # millions of rows: "what did this run *not* see" is then a single indexed comparison
    # against the run's start, and it stays correct when a crash interrupts the run.
    Column("last_seen_at", DateTime(timezone=True), nullable=True),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # A composite foreign key, not two independent ones: it makes invariant 1 structural â
    # a file's workspace *is* its folder's workspace, so no code path can file a row into
    # another workspace's tree, which would be a permission leak rather than a typo.
    # Deferrable, initially immediate: it fires per statement like any other constraint, and
    # only the cross-workspace folder move asks to hold it until commit â that operation
    # rewrites both halves of the pair, and either half alone looks like a violation
    # (F-015/FR-4).
    ForeignKeyConstraint(
        ["folder_id", "workspace_id"],
        ["folder.id", "folder.workspace_id"],
        ondelete="CASCADE",
        deferrable=True,
        initially="IMMEDIATE",
    ),
    # Sibling uniqueness covers **live** rows only, which is F-014/FR-1's "trashed items do
    # not reserve their path" made structural. A full constraint would make a file deleted on
    # the storage keep its name reserved by a trash entry, so re-uploading there would be
    # refused as a collision with something that is not on the disk at all.
    Index(
        "uq_file_live_name",
        "folder_id",
        "name_key",
        unique=True,
        postgresql_where=text("state = 'live'"),
    ),
    CheckConstraint(one_of("state", FILE_STATES), name="state_known"),
    CheckConstraint(f"octet_length(name) BETWEEN 1 AND {MAX_NAME_BYTES}", name="name_length"),
    Index("ix_file_workspace_id_state", "workspace_id", "state"),
    # The reconciliation sweep's query: live files in a subtree a run did not see
    # (F-001/FR-6). Folder-scoped rather than workspace-scoped because a subtree rescan must
    # never look outside its own root.
    Index("ix_file_folder_id_last_seen_at", "folder_id", "last_seen_at"),
)
"""A logical file, addressed as *(folder, name)* â its path is derived from the folder chain,
never stored (02 Â§ file). The UUID survives rename, move and new versions."""


file_version = Table(
    "file_version",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "file_id", UUID(as_uuid=True), ForeignKey("file.id", ondelete="CASCADE"), nullable=False
    ),
    Column("digest_algorithm", Text, nullable=False, server_default=text("'sha256'")),
    Column("content_hash", Text, nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    Column("media_type", Text, nullable=False),
    Column("media_class", Text, nullable=False),
    Column("origin", Text, nullable=False),
    Column("is_current", Boolean, nullable=False, server_default=text("true")),
    # Whether these bytes can still be produced (F-007/FR-9). True for a current version â
    # it *is* the file on disk â and for a superseded one the app snapshotted into
    # `versions/` before overwriting it. False once the bytes are gone: a file edited or
    # deleted directly on the storage was overwritten before the app could copy it, and
    # saying so is the honest answer rather than a restore that fails when tried.
    Column("restorable", Boolean, nullable=False, server_default=text("true")),
    # The mtime the file carried on disk when this version was recorded. The stat-scan
    # compares size and mtime before it hashes anything (ADR-0019), so recording it here is
    # what keeps a scan of 10 TB from being a re-hash of 10 TB.
    Column("modified_at", DateTime(timezone=True), nullable=True),
    _created_at(),
    # Exactly one current version per file, enforced rather than maintained: the alternative
    # â a `current_version_id` on `file` â is a circular foreign key that has to be deferred.
    Index("uq_file_version_current", "file_id", unique=True, postgresql_where=text("is_current")),
    # Reuse of extraction results and duplicate detection both start from "who else has these
    # bytes?" (04 Â§ identification, F-013).
    Index("ix_file_version_content_hash", "content_hash"),
    CheckConstraint("size_bytes >= 0", name="size_not_negative"),
    CheckConstraint(one_of("origin", VERSION_ORIGINS), name="origin_known"),
    CheckConstraint(one_of("media_class", MEDIA_CLASSES), name="media_class_known"),
    CheckConstraint(one_of("digest_algorithm", DIGEST_ALGORITHMS), name="digest_algorithm_known"),
)
"""An immutable snapshot of a file's content, identified by its hash (02 Â§ FileVersion)."""


#: Why an item is in the trash (F-014/FR-3). Phase 1 writes only `detected_on_disk`: a scan
#: can capture a deletion that already happened, but there is no way to delete through the app
#: until phase 4.
TRASH_ORIGINS = ("in_app", "detected_on_disk")


trash_entry = Table(
    "trash_entry",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "file_id", UUID(as_uuid=True), ForeignKey("file.id", ondelete="CASCADE"), nullable=False
    ),
    Column("origin", Text, nullable=False),
    # Every deletion belongs to a batch, so a mass deletion is restorable in one call
    # (F-014/FR-5). For a scan-detected deletion the batch **is** the run, which is exactly
    # the unit a user wants back after a share failed to mount.
    Column("batch_id", UUID(as_uuid=True), nullable=False),
    # Where the file was when it was trashed. Paths are derived from the folder chain
    # everywhere else; recorded here because a trash listing has to name a place that may no
    # longer be reachable by walking (F-014/FR-3, the F-011/FR-9 pattern).
    Column("path", Text, nullable=False),
    Column("trashed_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # NULL when nobody did it: a scan discovering a deletion that already happened on the
    # storage has no person to name (07 Â§ the audit trail).
    Column("trashed_by", UUID(as_uuid=True), ForeignKey("app_user.id", ondelete="SET NULL")),
    Column("purge_after", DateTime(timezone=True), nullable=False),
    _created_at(),
    # One entry per trashed file. A file restored and trashed again gets a new entry, because
    # the old one is deleted on restore rather than kept as history â the event log is what
    # keeps history (ADR-0007).
    UniqueConstraint("file_id"),
    CheckConstraint(one_of("origin", TRASH_ORIGINS), name="origin_known"),
    CheckConstraint(f"octet_length(path) <= {MAX_PATH_BYTES}", name="path_length"),
    Index("ix_trash_entry_batch_id", "batch_id"),
    # The janitor's question in phase 4 ("what is past its deadline"), and the ordering a
    # trash listing uses.
    Index("ix_trash_entry_purge_after", "purge_after"),
)
"""Why a file is in the trash, and until when (F-014). **Restorability is not stored** â it is
derived from whether any of the file's versions still has its bytes (`file_version.restorable`),
so it cannot go stale behind an app-mediated snapshot that happened later.

The deadline **is** stored, for the opposite reason: F-014's promise is that nothing leaves the
trash before its deadline, and a deadline computed at read time from a setting could be pulled
forward by changing that setting â which is that promise being broken. `trash.RETENTION` is
where the number comes from today."""


#: What an upload does when a live file already occupies its target path (F-001/FR-7).
#: `reject` is the default: overwriting is a decision a client makes explicitly.
UPLOAD_CONFLICT_MODES = ("reject", "new_version")

#: An upload session's life. `open` is the only state a client can act on; the rest are
#: terminal, which is what lets the janitor collect the staged bytes.
UPLOAD_STATES = ("open", "completed", "cancelled", "expired", "failed")


upload_session = Table(
    "upload_session",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "workspace_id",
        UUID(as_uuid=True),
        ForeignKey("workspace.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # Only its creator may drive a session. Not derived from the workspace's owner because
    # grants (phase 4) will let someone else upload into a workspace they do not own.
    Column(
        "created_by",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=False,
    ),
    # Resolved once, at creation: `HEAD` and `PATCH` then need no re-validation, and finalize
    # knows exactly where the bytes are going.
    Column("target_path", Text, nullable=False),
    Column("declared_length", BigInteger, nullable=True),
    Column("declared_hash", Text, nullable=True),
    Column("media_type", Text, nullable=True),
    Column("interop_version", SmallInteger, nullable=True),
    # Decided at creation, because that is where the client can be told "no" before it spends
    # an hour uploading â and because finalize may run in a much later request.
    Column("if_exists", Text, nullable=False, server_default=text("'reject'")),
    # The offset the client may rely on: bytes are fsync'd before this advances, never after
    # (ADR-0017). Staged bytes beyond it were never acknowledged and are truncated on resume.
    Column("committed_offset", BigInteger, nullable=False, server_default=text("0")),
    Column("state", Text, nullable=False, server_default=text("'open'")),
    Column("file_id", UUID(as_uuid=True), ForeignKey("file.id", ondelete="SET NULL")),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint(one_of("state", UPLOAD_STATES), name="state_known"),
    CheckConstraint(one_of("if_exists", UPLOAD_CONFLICT_MODES), name="if_exists_known"),
    CheckConstraint("committed_offset >= 0", name="offset_not_negative"),
    CheckConstraint(
        "declared_length IS NULL OR committed_offset <= declared_length",
        name="offset_within_length",
    ),
    CheckConstraint(f"octet_length(target_path) <= {MAX_PATH_BYTES}", name="target_path_length"),
    # The expiry sweep reads only live sessions, which is the whole table's hot query.
    Index(
        "ix_upload_session_expires_at",
        "expires_at",
        postgresql_where=text("state = 'open'"),
    ),
    Index("ix_upload_session_workspace_id_created_at", "workspace_id", "created_at"),
)
"""A resumable upload in progress: the durable row that makes an interrupted multi-gigabyte
upload resumable across restarts (ADR-0017, 03 Â§ uploads). Its staged bytes live in the
workspace's own `.workspace/staging/` area, named after this id, so the janitor can attribute
and collect them."""


#: What started a scan. `initial` is the import a freshly provisioned workspace arms for
#: itself; the others are ADR-0019's three paths, which are all the same operation.
SCAN_TRIGGERS = ("initial", "scheduled", "manual", "watcher")

#: A scan's life. `running` covers a scan that a crash interrupted, because the operation
#: that owns it will be claimed again and resume from the frontier.
SCAN_STATES = ("running", "completed", "failed", "cancelled")

#: What a scan reports instead of registering (ADR-0019). Both are *facts about the tree*,
#: never errors: a collision means two names the app cannot tell apart, a skipped entry means
#: a symlink, and neither is ever resolved by touching the user's files.
SCAN_FINDING_KINDS = ("conflict", "skipped")


scan_run = Table(
    "scan_run",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "workspace_id",
        UUID(as_uuid=True),
        ForeignKey("workspace.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("trigger", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'running'")),
    # The subtree this run covers, workspace-relative; empty means the whole workspace
    # (F-001's API surface offers a subtree rescan).
    Column("root_path", Text, nullable=False, server_default=text("''")),
    # The operation that owns this run. Not a foreign key on purpose: terminal operation rows
    # are pruned (12 Â§ queue hygiene), and a finished run's history must outlive that.
    Column("operation_id", UUID(as_uuid=True), nullable=False),
    # Progress, updated with each batch so a 10 TB import is observable while it runs
    # (F-001/FR-5) rather than only when it finishes.
    Column("directories_scanned", BigInteger, nullable=False, server_default=text("0")),
    Column("files_seen", BigInteger, nullable=False, server_default=text("0")),
    Column("files_registered", BigInteger, nullable=False, server_default=text("0")),
    # The four things reconciliation can conclude about a file it already knew (F-001/FR-6).
    # Separate columns rather than one "reconciled" number because they mean very different
    # things to whoever is watching: `trashed` climbing on a scheduled pass is how an operator
    # notices a share that half-unmounted.
    Column("files_changed", BigInteger, nullable=False, server_default=text("0")),
    Column("files_moved", BigInteger, nullable=False, server_default=text("0")),
    Column("files_trashed", BigInteger, nullable=False, server_default=text("0")),
    Column("files_restored", BigInteger, nullable=False, server_default=text("0")),
    Column("conflicts", BigInteger, nullable=False, server_default=text("0")),
    Column("skipped", BigInteger, nullable=False, server_default=text("0")),
    # Folders whose identity survived an external rename, and the ones where the evidence was
    # ambiguous and a new identity was created instead (F-015/FR-7).
    Column("folders_transferred", BigInteger, nullable=False, server_default=text("0")),
    Column("folders_ambiguous", BigInteger, nullable=False, server_default=text("0")),
    Column("started_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("error", Text, nullable=True),
    CheckConstraint(one_of("trigger", SCAN_TRIGGERS), name="trigger_known"),
    CheckConstraint(one_of("state", SCAN_STATES), name="state_known"),
    # One run per operation, which is what makes a re-claimed operation resume its own run
    # instead of starting a second one.
    UniqueConstraint("operation_id"),
    Index("ix_scan_run_workspace_id_started_at", "workspace_id", "started_at"),
    # At most one scan per workspace at a time: a second concurrent traversal of the same
    # tree would double the IO and race its own registrations.
    Index(
        "uq_scan_run_active",
        "workspace_id",
        unique=True,
        postgresql_where=text("state = 'running'"),
    ),
)
"""One traversal of a workspace (or a subtree of one). Holds the progress a client polls and
the durable state a crash resumes from (12 Â§ job atomicity)."""


scan_frontier = Table(
    "scan_frontier",
    metadata,
    Column(
        "run_id",
        UUID(as_uuid=True),
        ForeignKey("scan_run.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    # Workspace-relative; the empty string is the workspace root.
    Column("path", Text, primary_key=True),
    # The folder row for *this* directory, resolved when the directory was discovered â so
    # processing it costs no walk from the root, and a 100k-directory tree does not pay
    # O(depth) queries per batch.
    Column(
        "folder_id", UUID(as_uuid=True), ForeignKey("folder.id", ondelete="CASCADE"), nullable=False
    ),
    _created_at(),
    CheckConstraint(f"octet_length(path) <= {MAX_PATH_BYTES}", name="path_length"),
)
"""**The durable cursor.** Directories a run has discovered and not yet processed: one batch
pops a directory, registers what is in it, pushes its subdirectories and deletes its own row â
all in one transaction, which is the checkpoint 12 Â§ job atomicity requires.

Directories that *vanished* stay on the frontier deliberately. Popping one that is no longer
there is an empty listing, so a subtree deleted on disk needs no special case at any depth."""


scan_blocked = Table(
    "scan_blocked",
    metadata,
    Column(
        "run_id",
        UUID(as_uuid=True),
        ForeignKey("scan_run.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "folder_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    _created_at(),
)
"""Directories this run **could not read** â permissions, a path that resolved outside the
workspace, a mount that went away. F-001/FR-16 is enforced from this table: the reconciliation
sweep excludes every descendant of a blocked folder, because "I could not look" says nothing
about what is inside and must never be reconciled as "it is not there".

Normally empty. Per run rather than on the folder row, because the fact is about one traversal:
the directory readable again next hour is reconciled then."""


scan_finding = Table(
    "scan_finding",
    metadata,
    # An integer rather than a UUID: a symlink farm can produce a great many of these, and
    # they are only ever read as an ordered page.
    Column("id", BigInteger, Identity(always=True), primary_key=True),
    Column(
        "run_id", UUID(as_uuid=True), ForeignKey("scan_run.id", ondelete="CASCADE"), nullable=False
    ),
    Column("kind", Text, nullable=False),
    Column("path", Text, nullable=False),
    # The other spelling for a collision, the reason for a skip. Prose the user has to act on.
    Column("detail", Text, nullable=False),
    _created_at(),
    CheckConstraint(one_of("kind", SCAN_FINDING_KINDS), name="kind_known"),
    Index("ix_scan_finding_run_id_id", "run_id", "id"),
)
"""What a scan **reported instead of registering** (F-001/FR-11, FR-12). The user resolves a
conflict by renaming something; the app never renames, moves or deletes a file to fix one."""


scan_relocation = Table(
    "scan_relocation",
    metadata,
    Column(
        "run_id",
        UUID(as_uuid=True),
        ForeignKey("scan_run.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "from_folder_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "to_folder_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("files", BigInteger, nullable=False, server_default=text("0")),
    # Child folders whose own identity this run transferred into the destination. The evidence a
    # directory holding nothing but subdirectories leaves behind (F-015/FR-7): its files cannot
    # vouch for it, but the folders it used to contain can.
    Column("folders", BigInteger, nullable=False, server_default=text("0")),
    _created_at(),
    CheckConstraint("files >= 0 AND folders >= 0", name="counts_not_negative"),
    CheckConstraint("from_folder_id <> to_folder_id", name="from_is_not_to"),
)
"""**Where a directory's content went**, counted per run — the evidence for F-015/FR-7.

A file that moved no longer says where it came from, and neither does anything else: the row was
updated in place. So the move is counted here as it happens, one row per source/destination pair,
which is also what keeps the identity pass proportional to what moved rather than to how many
dead folders the index holds.

Per run rather than on the folder row, for the same reason `scan_blocked` is: the fact is about
one traversal. A pair that means "renamed" this hour means nothing next hour."""


# --------------------------------------------------------------- the extractor registry
#
# 05-extractor-contract.md, ADR-0020. An extractor is a container that analyses files; the
# registry is what the core knows about it.

#: The contract version this core speaks. Extractors declare theirs and are refused if it is
#: not this one — the version is the compatibility promise (05 § compatibility rules).
EXTRACTOR_API_VERSION = "v1"

#: Output kinds a result envelope may carry (05 § result envelope).
EXTRACTOR_OUTPUT_KINDS = (
    "metadata",
    "text_segments",
    "tags",
    "embeddings",
    "derived_assets",
    "renditions",
    "faces",
)

#: A scheduler hint, not a priority: the core assigns priority from (output kind, trigger)
#: (04 § prioritization).
EXTRACTOR_COST_CLASSES = ("light", "medium", "heavy")

EXTRACTOR_GPU_MODES = ("none", "optional", "required")

#: `outbound` is the explicit, admin-visible opt-in of a remote-AI extractor; enforcement is
#: the compose topology (ADR-0021), so this column records declared intent.
EXTRACTOR_NETWORK_MODES = ("none", "outbound")

#: The three output namespaces that have exactly one producer each (ADR-0020 § registration).
EXTRACTOR_CLAIM_TYPES = ("rendition", "derived_asset", "embedding_space")

#: Identifiers chosen by extractor authors — extractor ids, rendition kinds, derived-asset
#: kinds, embedding spaces. Lower-case kebab, because they end up in operation kinds
#: (`extract.pdf-text`), in URLs, and in derived-store paths.
SLUG_PATTERN = r"^[a-z0-9]+(-[a-z0-9]+)*$"
MAX_SLUG_LENGTH = 64


extractor = Table(
    "extractor",
    metadata,
    # The manifest's `id` *is* the key. It is stable, chosen once by the extractor's author,
    # and already the text every other mention is written in: the operation kind
    # (`extract.pdf-text`), the admin URL, the provenance stamp on every derived row. A
    # surrogate UUID would be an alias nothing outside this table ever used.
    Column("id", Text, primary_key=True),
    # Everything the manifest supplies is NULL until the container first registers: an admin
    # provisions the id and its token, and the container declares what it can do (ADR-0020).
    # So a row with no manifest is not broken — it is an extractor that has never started.
    Column("version", Text, nullable=True),
    Column("api_version", Text, nullable=True),
    Column("model_name", Text, nullable=True),
    Column("model_version", Text, nullable=True),
    Column("cost_class", Text, nullable=True),
    Column("gpu", Text, nullable=True),
    Column("network", Text, nullable=True),
    # The manifest as registered: parsed, unknown fields preserved. Kept whole because the
    # contract tolerates fields this core does not know yet (05 § compatibility rules), and an
    # admin reviewing an extractor should see what it declared, not only what we understood.
    # Routing reads it too — at 10-30 extractors a scan of this table beats normalising every
    # accepted MIME pattern into its own row.
    Column("manifest", JSONB, nullable=True),
    # Whether the core routes work here. One meaning only: a disabled extractor still
    # authenticates and still registers (keeping its manifest current), it just gets no jobs —
    # which is how `face-detect` ships installed but inactive (ADR-0011).
    Column("enabled", Boolean, nullable=False, server_default=text("true")),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("registered_at", DateTime(timezone=True), nullable=True),
    # Last authenticated call, so an admin can tell a running extractor from an absent one.
    Column("last_seen_at", DateTime(timezone=True), nullable=True),
    CheckConstraint(f"id ~ '{SLUG_PATTERN}'", name="id_slug"),
    CheckConstraint(f"length(id) BETWEEN 1 AND {MAX_SLUG_LENGTH}", name="id_length"),
    # The manifest and everything derived from it arrive together, in one statement, or not at
    # all — so "registered" is one fact rather than four columns that could disagree.
    CheckConstraint(
        "(manifest IS NULL) = (version IS NULL)"
        " AND (manifest IS NULL) = (api_version IS NULL)"
        " AND (manifest IS NULL) = (registered_at IS NULL)",
        name="registration_is_all_or_nothing",
    ),
    CheckConstraint(
        f"cost_class IS NULL OR {one_of('cost_class', EXTRACTOR_COST_CLASSES)}",
        name="cost_class_known",
    ),
    CheckConstraint(f"gpu IS NULL OR {one_of('gpu', EXTRACTOR_GPU_MODES)}", name="gpu_known"),
    CheckConstraint(
        f"network IS NULL OR {one_of('network', EXTRACTOR_NETWORK_MODES)}",
        name="network_known",
    ),
)
"""A registered extractor (05 § registration). Provisioned by an admin, described by itself."""


extractor_token = Table(
    "extractor_token",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "extractor_id",
        Text,
        ForeignKey("extractor.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    # The SHA-256 only, exactly as for a personal access token: a database dump is not a set
    # of live credentials (07 § tokens & credentials).
    Column("token_hash", Text, nullable=False),
    _created_at(),
    Column("last_used_at", DateTime(timezone=True), nullable=True),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("token_hash"),
    # A name is how an admin recognises one token among an extractor's several during a
    # rotation, so it has to be unambiguous within the extractor.
    UniqueConstraint("extractor_id", "name"),
    CheckConstraint("length(name) BETWEEN 1 AND 100", name="name_length"),
)
"""The credential one extractor container authenticates with (ADR-0020).

Bound to the extractor id rather than to a user: it says *which extractor this is*, which is
what stops one extractor from claiming another's jobs or stamping another's provenance."""


extractor_claim = Table(
    "extractor_claim",
    metadata,
    Column("claim_type", Text, nullable=False),
    Column("kind", Text, nullable=False),
    Column(
        "extractor_id",
        Text,
        ForeignKey("extractor.id", ondelete="CASCADE"),
        nullable=False,
    ),
    _created_at(),
    # The single-provider rule as a constraint rather than a check in application code: two
    # extractors cannot both produce `searchable-pdf`, so "which one wins" has no answer to
    # get wrong (ADR-0020 § registration rules).
    PrimaryKeyConstraint("claim_type", "kind"),
    Index("ix_extractor_claim_extractor_id", "extractor_id"),
    CheckConstraint(one_of("claim_type", EXTRACTOR_CLAIM_TYPES), name="claim_type_known"),
    CheckConstraint(f"kind ~ '{SLUG_PATTERN}'", name="kind_slug"),
    CheckConstraint(f"length(kind) BETWEEN 1 AND {MAX_SLUG_LENGTH}", name="kind_length"),
)
"""Which extractor owns each exclusive output name — rendition kinds, derived-asset kinds and
embedding spaces (ADR-0020). Segments, metadata and tags are deliberately absent: those are
multi-producer, and every row of them carries the run that produced it instead."""


#: One run of one extractor over one file version. The states are the *job's* states
#: ([05 § job lifecycle](../../../specs/05-extractor-contract.md#job-lifecycle)), which is why
#: this is the operation vocabulary rather than a second one beside it.
EXTRACTION_RUN_STATES = OPERATION_STATES

#: The first generation. Reprocessing increments it per run (ADR-0004); nothing does yet.
FIRST_GENERATION = 1


extraction_run = Table(
    "extraction_run",
    metadata,
    # The job's id *is* the run's id (ADR-0020): one row of durable intent in `operation`, one
    # row of durable provenance here, and an extractor that knows one knows the other.
    Column("id", UUID(as_uuid=True), primary_key=True),
    # RESTRICT, like the event log's actor: provenance outlives convenience, so retiring an
    # extractor is a decision about derived data rather than a cascade nobody asked for.
    Column(
        "extractor_id",
        Text,
        ForeignKey("extractor.id", ondelete="RESTRICT"),
        nullable=False,
    ),
    Column(
        "file_version_id",
        UUID(as_uuid=True),
        ForeignKey("file_version.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("generation", Integer, nullable=False, server_default=text(str(FIRST_GENERATION))),
    Column("state", Text, nullable=False, server_default=text("'queued'")),
    # What actually ran, stamped when the job is claimed rather than when it is created: an
    # extractor upgraded in between is a different program, and provenance has to name the one
    # that produced the rows (02 § invariants #3).
    Column("extractor_version", Text, nullable=True),
    Column("model_version", Text, nullable=True),
    # Which derived asset this run is *about*, for a chained job — a keyframe, a converted PDF.
    # NULL means the file's own bytes. It is part of the identity of the work, which is why the
    # uniqueness below counts it: one video's fifty keyframes are fifty jobs for one extractor,
    # not one (12 § job atomicity — large work is made resumable by decomposition).
    Column("input_asset_id", UUID(as_uuid=True), nullable=True),
    # Set when this run's rows were copied from an earlier run over byte-identical content
    # rather than computed ([F-009/FR-8](../../../features/F-009-reprocessing.md)). Provenance
    # has to say so: the rows are this version's, and the analysis happened once.
    Column(
        "reused_from",
        UUID(as_uuid=True),
        ForeignKey("extraction_run.id", ondelete="SET NULL"),
        nullable=True,
    ),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("error", Text, nullable=True),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # What was *asked for*, when the answer is not "everything this extractor does": `page:3`,
    # `rendition:searchable-pdf`. NULL is the ordinary case — routing asking an extractor to do
    # its job over an input — and a value is on-demand work somebody requested (F-028/FR-7,
    # FR-8). It is part of the key below because two page requests over one PDF are two
    # different pieces of work, and without it the second would converge onto the first.
    Column("variant", Text, nullable=True),
    # One run per (version, extractor, generation, input, variant) — the structural half of
    # "routing is idempotent", so a re-detected file cannot grow a second run of the same work.
    # `NULLS NOT DISTINCT` is what makes that true for the common case: two runs over a file's
    # own bytes both carry NULLs here, and PostgreSQL would otherwise consider them different.
    UniqueConstraint(
        "file_version_id",
        "extractor_id",
        "generation",
        "input_asset_id",
        "variant",
        # Named explicitly: the convention's generated name would be 71 characters, and
        # PostgreSQL truncates at 63 — which is a silent rename rather than an error.
        name="uq_extraction_run_one_per_input",
        postgresql_nulls_not_distinct=True,
    ),
    # `use_alter` because these two tables point at each other: a run names the derived asset it
    # is *about* (a keyframe, a converted PDF), and every asset names the run that produced it.
    # Both are wanted, so the cycle is real — and one of the constraints has to be added after
    # both tables exist rather than inside a `CREATE TABLE`.
    ForeignKeyConstraint(
        ["input_asset_id"],
        ["derived_asset.id"],
        name="fk_extraction_run_input_asset_id_derived_asset",
        ondelete="CASCADE",
        use_alter=True,
    ),
    CheckConstraint(one_of("state", EXTRACTION_RUN_STATES), name="state_known"),
    CheckConstraint("generation >= 1", name="generation_positive"),
    # The per-file status query (04 § status & observability): every run of one version.
    Index("ix_extraction_run_file_version_id", "file_version_id"),
    # And its per-extractor counterpart — queue depth and failure rate for one extractor.
    Index("ix_extraction_run_extractor_id_state", "extractor_id", "state"),
)
"""**The provenance anchor.** Every derived row references the run that produced it (02 §
invariants #3), and this table is deliberately not the queue: terminal operation rows are
pruned once history outgrows them (12 § queue hygiene, Q33), while "which extractor version
produced this" has to stay answerable forever.

It is also why extraction needs no event per run. A successful run *is* this row — queryable,
stamped, and joined to its outputs — so duplicating it into the log would add millions of rows
saying what a table already says. Failures still reach the log, through the operation layer's
own `operation.dead_lettered`."""


# ------------------------------------------------------------------- what extraction produces
#
# Three tables, one shape: a row of derived data, the version it describes, and the run that
# produced it. That last column is [02 § invariants](../../../specs/02-domain-model.md#invariants)
# #3 made structural — every derived row can name the extractor, version, model and generation
# behind it, because it points at the run that carries them.

#: How a metadata value is stored, which is also what can be asked of it
#: ([02 § MetadataEntry](../../../specs/02-domain-model.md#metadataentry)).
METADATA_VALUE_TYPES = (
    "string",
    "text",
    "integer",
    "float",
    "boolean",
    "datetime",
    "date",
    "duration",
    "geo",
    "json",
)

#: Who put a value there (ADR-0004). `confirmed`/`rejected` are the tag state machine's, and
#: appear on `file_tag` rather than here: there is nothing to confirm about a page count.
METADATA_PROVENANCE = ("auto", "manual")

#: What an anchor points at ([02 § Segment](../../../specs/02-domain-model.md#segment)). The
#: payload shape per kind lives in `results.py`; the vocabulary is fixed here because a listing
#: that does not know how to render an anchor cannot show a search hit's position.
SEGMENT_ANCHOR_KINDS = ("page", "time", "line", "sheet", "region", "whole")


metadata_entry = Table(
    "metadata_entry",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "file_version_id",
        UUID(as_uuid=True),
        ForeignKey("file_version.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # CASCADE, unlike the run's own reference to its extractor: derived data is regenerable by
    # definition (02 § invariants #5), so a run and its outputs go together or not at all.
    Column(
        "run_id",
        UUID(as_uuid=True),
        ForeignKey("extraction_run.id", ondelete="CASCADE"),
        nullable=True,
    ),
    Column("key", Text, nullable=False),
    Column("value_type", Text, nullable=False),
    Column("provenance", Text, nullable=False, server_default=text("'auto'")),
    Column("confidence", Float, nullable=True),
    Column("generation", Integer, nullable=False, server_default=text(str(FIRST_GENERATION))),
    # One column per storage class rather than one JSON blob, because the type is what decides
    # what can be *asked*: a range over `taken_at`, a facet over `camera`, a radius around `gps`
    # (02 § MetadataEntry). A blob would make every one of those a cast at query time.
    Column("value_text", Text, nullable=True),
    Column("value_number", Float, nullable=True),
    Column("value_boolean", Boolean, nullable=True),
    Column("value_time", DateTime(timezone=True), nullable=True),
    # Two columns rather than a `point` or PostGIS: a bounding box over two indexed floats is
    # what the map view asks of `gps` (F-002/FR-17), and it needs no extension, no custom type
    # and no argument about whether x is latitude (ADR-0001 keeps the datastore plain).
    Column("value_latitude", Float, nullable=True),
    Column("value_longitude", Float, nullable=True),
    Column("value_json", JSONB, nullable=True),
    _created_at(),
    CheckConstraint(one_of("value_type", METADATA_VALUE_TYPES), name="value_type_known"),
    CheckConstraint(one_of("provenance", METADATA_PROVENANCE), name="provenance_known"),
    CheckConstraint("length(key) BETWEEN 1 AND 100", name="key_length"),
    CheckConstraint(
        "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)", name="confidence_is_a_ratio"
    ),
    # A run is required for `auto` and absent for `manual`: a machine-derived fact that cannot
    # name what derived it is not traceable, and a user's edit has a user, not a run.
    CheckConstraint(
        "(provenance = 'auto') = (run_id IS NOT NULL)", name="auto_values_name_their_run"
    ),
    # The per-file read: every fact about one version, in one indexed lookup.
    Index("ix_metadata_entry_file_version_id_key", "file_version_id", "key"),
    # And the per-key reads search will want: a facet over one key, a range over another.
    Index("ix_metadata_entry_key_value_text", "key", "value_text"),
    Index("ix_metadata_entry_key_value_number", "key", "value_number"),
    Index("ix_metadata_entry_key_value_time", "key", "value_time"),
    Index("ix_metadata_entry_run_id", "run_id"),
    # The map view's read: everything with a position, bounded by a box.
    Index("ix_metadata_entry_value_latitude_value_longitude", "value_latitude", "value_longitude"),
)
"""A typed fact about one file version — EXIF, page count, detected language, a bounding box.

Unknown keys are stored, typed and queryable like any other; the well-known registry
([02 § MetadataEntry](../../../specs/02-domain-model.md#metadataentry)) only says which keys
built-in features bind to."""


segment = Table(
    "segment",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "file_version_id",
        UUID(as_uuid=True),
        ForeignKey("file_version.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column(
        "run_id",
        UUID(as_uuid=True),
        ForeignKey("extraction_run.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("generation", Integer, nullable=False, server_default=text(str(FIRST_GENERATION))),
    # Position within the run's output, so "the third segment of page 2" has a stable identity
    # across reads without depending on the anchor being orderable.
    Column("ordinal", Integer, nullable=False),
    Column("text", Text, nullable=False),
    Column("anchor_kind", Text, nullable=False),
    # The anchor's payload — page number, time range, line range, sheet and rows, image region.
    # JSONB rather than a column per kind: an anchor is *returned* with a hit rather than
    # queried across kinds, and a plugin with a new kind of position should not need a migration
    # (05 § result envelope). What is fixed is the vocabulary of kinds and each one's shape.
    Column("anchor", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    # OCR confidence, where the extractor reports one (F-004/FR-2).
    Column("confidence", Float, nullable=True),
    Column("language", Text, nullable=True),
    _created_at(),
    CheckConstraint(one_of("anchor_kind", SEGMENT_ANCHOR_KINDS), name="anchor_kind_known"),
    CheckConstraint("ordinal >= 0", name="ordinal_not_negative"),
    CheckConstraint(
        "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)", name="confidence_is_a_ratio"
    ),
    UniqueConstraint("run_id", "ordinal"),
    # The per-file read, in the order a document is read in.
    Index("ix_segment_file_version_id_ordinal", "file_version_id", "ordinal"),
)
"""The positional unit of search ([06](../../../specs/06-search.md)): a span of text and where it
is. This is what lets a hit say *pages 1, 3 and 7* or *at 04:12* rather than only *this file*.

The full-text index over `text` arrives with search in phase 3, together with the language
question it depends on (Q14) — a `tsvector` needs an analyser, and picking one before the query
exists would be guessing."""


derived_asset = Table(
    "derived_asset",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "file_version_id",
        UUID(as_uuid=True),
        ForeignKey("file_version.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column(
        "run_id",
        UUID(as_uuid=True),
        ForeignKey("extraction_run.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("generation", Integer, nullable=False, server_default=text(str(FIRST_GENERATION))),
    # An open vocabulary on purpose (ADR-0008): `thumb`, `page`, `keyframe`, `waveform`, and
    # whatever a plugin invents. What is *not* open is who may produce each one — the registry
    # enforces one provider per derived-asset kind (ADR-0020).
    Column("kind", Text, nullable=False),
    # The filename inside the source hash's directory, chosen by the extractor and validated by
    # the core (`derived.py`): the core owns the location, the extractor owns the name.
    Column("name", Text, nullable=False),
    Column("media_type", Text, nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    # The asset's *own* digest, which is how it was staged and how its integrity is checked.
    # Its *location* comes from the source version's hash instead (09 § storage), which is what
    # gives duplicate files one set of assets.
    Column("content_hash", Text, nullable=False),
    Column("digest_algorithm", Text, nullable=False, server_default=text("'sha256'")),
    # Whatever distinguishes this asset from its siblings of the same kind: `{"size": 256}`,
    # `{"page": 3}`, `{"at_ms": 4200}`. Returned with the asset so a client can ask for the
    # right one without knowing the naming convention.
    Column("params", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    # Set when this asset is a downloadable alternative form of the whole file rather than a
    # fragment of it: a searchable PDF, an `.srt` (ADR-0008). The kind vocabulary is the
    # manifest's; one producer per kind, enforced at registration.
    Column("rendition_kind", Text, nullable=True),
    _created_at(),
    CheckConstraint("size_bytes >= 0", name="size_not_negative"),
    CheckConstraint("length(name) BETWEEN 1 AND 64", name="name_length"),
    CheckConstraint(one_of("digest_algorithm", DIGEST_ALGORITHMS), name="digest_algorithm_known"),
    # One asset per name per version and generation. The name is what addresses it on disk, so
    # two rows claiming the same one would be two rows describing the same bytes.
    UniqueConstraint("file_version_id", "name", "generation"),
    Index("ix_derived_asset_file_version_id_kind", "file_version_id", "kind"),
    Index("ix_derived_asset_run_id", "run_id"),
    # The reverse lookup the janitor needs: is anything still referencing these bytes?
    Index("ix_derived_asset_content_hash", "content_hash"),
)
"""A generated artifact in the derived store — thumbnail, page render, keyframe, transcript,
rendition. Fully regenerable (02 § invariants #5), which is why every column here can be
recomputed from the source plane and why deleting one is never data loss."""


# ------------------------------------------------------ the tag vocabulary, and what carries one
#
# ADR-0006 and [F-003](../../../features/F-003-tagging.md). One global, admin-governed DAG; a
# file or folder carries a flat list of the **most specific** tags it earns; a broad search
# expands downward over the closure at query time. No ancestor is ever written onto a file, and
# that is the whole point — restructuring the taxonomy touches zero file rows, and a forest photo
# tagged `tree` never acquires `garden` because some path led there.

#: Where a tag stands in the vocabulary (ADR-0006). Only `active` tags are vocabulary —
#: appliable, searchable, completable. `suggested` is the auto-tagger's quarantine, and
#: `rejected` is a soft removal that keeps the name: a suppression record, so a later
#: extraction run cannot re-create a suggestion an admin already turned down.
TAG_STATUSES = ("active", "suggested", "rejected")

#: What a *user* said about one tag on one file (ADR-0004). `auto` is deliberately absent: a
#: machine's claim is derived data stamped with the run that produced it and belongs with the
#: other derived rows, while this table is curation and outlives every generation. Keeping the
#: two apart is what makes [02 § invariants](../../../specs/02-domain-model.md#invariants) #4
#: structural instead of merely tested — the path that replaces a generation's output has no
#: reason to name this table, and does not.
TAG_CURATION_STATES = ("manual", "confirmed", "rejected")

#: A tag name, in characters. Unlike a filename it is a label a person types: spaces are
#: allowed (and collapsed), case is preserved for display and folded for identity.
MAX_TAG_NAME_LENGTH = 100


tag = Table(
    "tag",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("status", Text, nullable=False, server_default=text("'active'")),
    # The admin who put it in the vocabulary — NULL for one a machine suggested, because an
    # extractor is not a user (ADR-0007) and an approved suggestion has no author to name.
    Column(
        "created_by",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=True,
    ),
    # Which run proposed it, for a `suggested` tag: the review queue's "where did this word come
    # from" (F-003/FR-12). SET NULL rather than CASCADE — a suggestion outlives the run that
    # made it, because deleting the word would undo an admin's pending decision.
    Column(
        "suggested_by_run_id",
        UUID(as_uuid=True),
        ForeignKey("extraction_run.id", ondelete="SET NULL"),
        nullable=True,
    ),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column(
        "reviewed_by",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=True,
    ),
    _created_at(),
    CheckConstraint(one_of("status", TAG_STATUSES), name="status_known"),
    # A decision has a decider and a moment, or neither: half a review record would be a
    # question nobody can answer later.
    CheckConstraint("(reviewed_at IS NULL) = (reviewed_by IS NULL)", name="review_is_whole"),
    # The review queue's read: every tag awaiting a decision (F-003/FR-12).
    Index("ix_tag_status", "status"),
)
"""A node in the one global tag vocabulary. Deliberately nameless: a tag's names live in
`tag_name`, because a tag has one canonical name *and* any number of synonyms, and "which
spellings mean this tag" is one question with one answer table."""


tag_name = Table(
    "tag_name",
    metadata,
    # The folded key **is** the primary key, and that is the point: a synonym and a canonical
    # name cannot both claim `car`, because they are rows in the same table. Two tables would
    # need a cross-table check no constraint can express, and the failure it would let through
    # is the worst kind — `car` meaning two things, resolved by whichever query ran first.
    Column("name_key", Text, primary_key=True),
    # As typed, for display. Case and spelling are the author's; identity is the key's.
    Column("name", Text, nullable=False),
    Column("tag_id", UUID(as_uuid=True), ForeignKey("tag.id", ondelete="CASCADE"), nullable=False),
    Column("is_alias", Boolean, nullable=False, server_default=text("false")),
    _created_at(),
    CheckConstraint(f"length(name) BETWEEN 1 AND {MAX_TAG_NAME_LENGTH}", name="name_length"),
    CheckConstraint("length(name_key) >= 1", name="key_present"),
    # Exactly one canonical name per tag; every other spelling of it is an alias.
    Index("uq_tag_name_canonical", "tag_id", unique=True, postgresql_where=text("NOT is_alias")),
    # Prefix completion (F-003/FR-8). A btree can serve `LIKE 'inv%'` only under an operator
    # class that ignores collation, so the index says which one — otherwise every keystroke
    # would be a sequential scan over the whole vocabulary.
    Index("ix_tag_name_prefix", "name_key", postgresql_ops={"name_key": "text_pattern_ops"}),
    # Every spelling of one tag: the alias list an admin edits, which the partial unique index
    # above cannot serve because it holds only the canonical rows.
    Index("ix_tag_name_tag_id", "tag_id"),
)
"""Every spelling that resolves to a tag — its canonical name and its aliases, in one table.

Aliases are what absorbs model-label drift (ADR-0006): an auto-tagger emitting `automobile`
lands on `car` without a new tag, and the taxonomy stays curated. They are also why completion
and resolution are the same lookup — typing `automobile` can offer `car`, because the name that
matched and the tag it means are one row apart."""


tag_edge = Table(
    "tag_edge",
    metadata,
    Column(
        "parent_id", UUID(as_uuid=True), ForeignKey("tag.id", ondelete="CASCADE"), primary_key=True
    ),
    Column(
        "child_id", UUID(as_uuid=True), ForeignKey("tag.id", ondelete="CASCADE"), primary_key=True
    ),
    _created_at(),
    CheckConstraint("parent_id <> child_id", name="no_self_parent"),
    # "What is directly under this tag" — the tree an admin UI renders one level at a time.
    Index("ix_tag_edge_child_id", "child_id"),
)
"""One *is-a* edge of the vocabulary DAG. **Multi-parent by design** (ADR-0006): `tree` sits
under `plant` and under `landscaping`, and neither placement is wrong. Cycles are refused when
an edge is added, which is what keeps the closure rebuild finite."""


tag_closure = Table(
    "tag_closure",
    metadata,
    Column(
        "ancestor_id",
        UUID(as_uuid=True),
        ForeignKey("tag.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "descendant_id",
        UUID(as_uuid=True),
        ForeignKey("tag.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("depth", Integer, nullable=False),
    CheckConstraint("depth >= 0", name="depth_not_negative"),
    CheckConstraint("(ancestor_id = descendant_id) = (depth = 0)", name="self_row_at_depth_zero"),
    # The other direction: every ancestor of one tag, which is what renders the breadcrumb
    # `nature / plant / tree` and what cycle detection asks before an edge is allowed.
    Index("ix_tag_closure_descendant_id", "descendant_id"),
)
"""Precomputed reachability, so `tag:nature` expands to every descendant in one indexed lookup
instead of a recursive query per search (ADR-0006).

Unlike the folder closure this graph is a DAG, so two tags can be connected by paths of
different lengths. `depth` is therefore the **shortest** one and the pair is the key: expansion
asks whether the row exists, and the number only renders a breadcrumb. One row per path would
answer neither question better and would grow combinatorially with every diamond."""


file_tag = Table(
    "file_tag",
    metadata,
    Column(
        "file_id", UUID(as_uuid=True), ForeignKey("file.id", ondelete="CASCADE"), primary_key=True
    ),
    Column(
        "tag_id", UUID(as_uuid=True), ForeignKey("tag.id", ondelete="CASCADE"), primary_key=True
    ),
    Column("provenance", Text, nullable=False),
    # Who said it. Required: curation without an author would be indistinguishable from a
    # machine's claim, and "stamped with Bob's user id" is what F-003 promises Alice sees.
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=False,
    ),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint(one_of("provenance", TAG_CURATION_STATES), name="provenance_known"),
    # Usage counts and, later, the tag filter's file set (F-003/FR-8, F-002).
    Index("ix_file_tag_tag_id", "tag_id"),
)
"""**A user's word on one tag for one file**: applied by hand, an auto tag confirmed, or an auto
tag rejected. One row per pair, because a person's position on a tag is one position.

On the *file*, not on a version: a tag describes the thing, so it survives a new upload of the
same document (02 § file — tags attach to the UUID). Machine claims go the other way, per
version, because they describe bytes that a new version replaces."""


file_auto_tag = Table(
    "file_auto_tag",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    # Per **version**, unlike curation: a machine's claim describes bytes, and a new version is
    # different bytes. The user's word is about the file and outlives every upload.
    Column(
        "file_version_id",
        UUID(as_uuid=True),
        ForeignKey("file_version.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column(
        "run_id",
        UUID(as_uuid=True),
        ForeignKey("extraction_run.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("tag_id", UUID(as_uuid=True), ForeignKey("tag.id", ondelete="CASCADE"), nullable=False),
    Column("generation", Integer, nullable=False, server_default=text(str(FIRST_GENERATION))),
    Column("confidence", Float, nullable=True),
    _created_at(),
    CheckConstraint(
        "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)", name="confidence_is_a_ratio"
    ),
    # One claim per tag per run: an extractor listing `cat` twice in one envelope means it once.
    # The *run* is in the key rather than only the version, because two extractors may both see
    # a cat and a generation swap must not take the other one's word away with it.
    UniqueConstraint("file_version_id", "tag_id", "run_id"),
    Index("ix_file_auto_tag_file_version_id", "file_version_id"),
    Index("ix_file_auto_tag_tag_id", "tag_id"),
    Index("ix_file_auto_tag_run_id", "run_id"),
)
"""**A machine's claim that a tag applies** — the fourth derived table, and the same shape as the
other three: the version it describes and the run that produced it
([02 § invariants](../../../specs/02-domain-model.md#invariants) #3).

Separate from `file_tag` on purpose. Reprocessing replaces a generation's output by deleting this
run's rows and writing the new ones (ADR-0004), and the table it must never touch is the one
holding what a person said — so that table is not in this path at all. Confidence lives here
because it is a property of the claim, not of the tag."""


folder_tag = Table(
    "folder_tag",
    metadata,
    Column(
        "folder_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "tag_id", UUID(as_uuid=True), ForeignKey("tag.id", ondelete="CASCADE"), primary_key=True
    ),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=False,
    ),
    _created_at(),
    Index("ix_folder_tag_tag_id", "tag_id"),
)
"""A tag on a directory ([F-015/FR-9](../../../features/F-015-folders.md)) — manual and
self-only. No provenance column and no confidence: extractors never run on folders, so there is
no machine claim to curate and nothing for the ADR-0004 state machine to do here.

A folder tag describes the folder. It does **not** match the files inside it; query-time
inheritance is deferred with its precedence rules unanswered (Q23)."""
