"""Table definitions and the single SQLAlchemy metadata they register on.

There are no ORM model classes by design (ADR-0012): tables are declared here as Core
`Table` objects, and rows map to Pydantic models at the API boundary (`schemas.py`).

Fixing the naming convention *before* the first table exists is deliberate: constraint
and index names become part of migrations the moment a table is created, and renaming
them later is a migration of its own.

Migrations are hand-written rather than autogenerated, so this file and the migration
history could drift. `tests/test_schema_matches_metadata.py` closes that gap by comparing
this metadata against a freshly migrated database.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Identity,
    Index,
    Integer,
    MetaData,
    SmallInteger,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import INET, JSONB, UUID

from store_everything.names import MAX_NAME_BYTES, MAX_PATH_BYTES

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)

#: Instance-level roles (07-identity-permissions-sharing.md § users).
USER_ROLES = ("admin", "member")

#: Personal-access-token scopes. `read` is least privilege for an agent or a read-only
#: integration; `full` acts as its user. Finer scopes are additive later.
TOKEN_SCOPES = ("read", "full")

#: Who acted (ADR-0007). `system` covers scheduled and startup work with no human behind it.
ACTOR_TYPES = ("user", "extractor", "system")


def _created_at() -> Column[datetime]:
    return Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now())


def one_of(column: str, allowed: tuple[str, ...]) -> str:
    """SQL for "this column holds one of these values".

    Written by hand rather than interpolating a Python tuple: a single-element tuple
    renders as `('x',)`, which is a syntax error, and the migration has to carry the
    identical text.
    """
    values = ", ".join(f"'{value}'" for value in allowed)
    return f"{column} IN ({values})"


app_user = Table(
    "app_user",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    # Stored lower-cased so "Alice@example.com" and "alice@example.com" are one account;
    # the check constraint makes that structural instead of a convention handlers remember.
    Column("email", Text, nullable=False),
    Column("display_name", Text, nullable=False),
    Column("password_hash", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("is_active", Boolean, nullable=False, server_default=text("true")),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("email"),
    CheckConstraint("email = lower(email)", name="email_lowercase"),
    CheckConstraint("length(email) BETWEEN 3 AND 320", name="email_length"),
    CheckConstraint("length(display_name) BETWEEN 1 AND 200", name="display_name_length"),
    CheckConstraint(one_of("role", USER_ROLES), name="role_known"),
)
"""Named `app_user` because `user` is a reserved word in PostgreSQL — quoting it forever
in hand-written SQL (ADR-0012) is a papercut with no upside."""


user_session = Table(
    "user_session",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # Only the SHA-256 of the token: a database dump can therefore not be replayed as a
    # set of live sessions (07 § tokens & credentials).
    Column("token_hash", Text, nullable=False),
    Column("user_agent", Text, nullable=True),
    _created_at(),
    Column("last_used_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # Rolling idle expiry: extended on use, so an active session survives and an abandoned
    # one lapses on its own.
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("token_hash"),
    Index("ix_user_session_user_id_created_at", "user_id", "created_at"),
)


access_token = Table(
    "access_token",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("token_hash", Text, nullable=False),
    Column("scope", Text, nullable=False),
    _created_at(),
    Column("last_used_at", DateTime(timezone=True), nullable=True),
    Column("expires_at", DateTime(timezone=True), nullable=True),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("token_hash"),
    # A name is how its owner recognizes a token in a list, so it has to be unambiguous.
    UniqueConstraint("user_id", "name"),
    CheckConstraint("length(name) BETWEEN 1 AND 100", name="name_length"),
    CheckConstraint(one_of("scope", TOKEN_SCOPES), name="scope_known"),
)


event = Table(
    "event",
    metadata,
    # A gapless-looking integer, not a UUID: the `/events` feed (phase 5) is a cursor over
    # this column. Note for that phase — identity values are assigned before commit, so
    # ids can become visible out of order under concurrency; a cursor feed needs a
    # commit-order-safe watermark rather than `id > $cursor` alone.
    Column("id", BigInteger, Identity(always=True), primary_key=True),
    Column("occurred_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("actor_type", Text, nullable=False),
    # RESTRICT, not CASCADE or SET NULL: the audit trail outlives everything else
    # (F-011/FR-2), so removing a user is a decision a later phase has to make
    # deliberately rather than a side effect of a foreign key.
    Column(
        "actor_user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=True,
    ),
    Column("action", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("resource_id", UUID(as_uuid=True), nullable=True),
    # Self-contained by design (F-011/FR-9): names and paths as they were at action time,
    # so history stays readable after the resource is purged.
    Column("details", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("request_id", Text, nullable=True),
    Column("client_ip", INET, nullable=True),
    CheckConstraint(one_of("actor_type", ACTOR_TYPES), name="actor_type_known"),
    CheckConstraint(
        "actor_type <> 'user' OR actor_user_id IS NOT NULL",
        name="user_actor_identified",
    ),
    Index("ix_event_occurred_at_id", "occurred_at", "id"),
    Index("ix_event_resource_type_resource_id_id", "resource_type", "resource_id", "id"),
    Index("ix_event_actor_user_id_id", "actor_user_id", "id"),
    # Serves the credential-abuse queries, which count recent events of one action
    # (07 § abuse protection).
    Index("ix_event_action_occurred_at", "action", "occurred_at"),
)
"""The append-only event log (ADR-0007). Writes ride the transaction of the change they
describe; `UPDATE` is refused by a database trigger, so immutability does not depend on
every future code path remembering it."""


#: The operation state machine (12-reliability.md § operation records). `queued` doubles as
#: "waiting for a retry" — a retryable failure returns to it with a later `next_due_at` — so
#: the only non-terminal states are `queued` and `running`.
OPERATION_STATES = (
    "queued",
    "running",
    "succeeded",
    "failed",
    "dead_letter",
    "cancelled",
    "superseded",
)

#: Nothing claims these again, and their idempotency key becomes free for reuse.
TERMINAL_OPERATION_STATES = ("succeeded", "failed", "dead_letter", "cancelled", "superseded")

#: Priority classes from 04-ingestion-pipeline.md § prioritization: 0 = interactive,
#: 1 = presence, 2 = searchability, 3 = heavy derived, 4 = reprocessing. Lower runs first.
MIN_PRIORITY, MAX_PRIORITY = 0, 4


operation = Table(
    "operation",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("kind", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'queued'")),
    Column("priority", SmallInteger, nullable=False, server_default=text("2")),
    # Counted on *claim*, not on failure: a job that OOM-kills its worker never reports an
    # error, and counting here is what dead-letters it anyway (12 § leases & fencing).
    Column("attempt", Integer, nullable=False, server_default=text("0")),
    Column("max_attempts", Integer, nullable=False),
    # The durable schedule. Retry backoff, periodic work and "run now" are all this column;
    # in-memory timers are forbidden (ADR-0010 rule 1).
    Column("next_due_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("leased_by", Text, nullable=True),
    Column("lease_expires_at", DateTime(timezone=True), nullable=True),
    # The cancellation channel: a worker learns of it from its heartbeat response rather
    # than from a signal, so cancellation survives a restart like everything else.
    Column("cancel_requested", Boolean, nullable=False, server_default=text("false")),
    Column("idempotency_key", Text, nullable=True),
    Column("payload", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("result", JSONB, nullable=True),
    Column("error", Text, nullable=True),
    # What the operation is about, so per-file and per-workspace status stays answerable
    # (04 § status & observability) without one table per operation kind.
    Column("subject_type", Text, nullable=True),
    Column("subject_id", UUID(as_uuid=True), nullable=True),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    CheckConstraint(one_of("state", OPERATION_STATES), name="state_known"),
    CheckConstraint(
        f"priority BETWEEN {MIN_PRIORITY} AND {MAX_PRIORITY}", name="priority_in_range"
    ),
    CheckConstraint("max_attempts > 0", name="max_attempts_positive"),
    CheckConstraint("attempt >= 0", name="attempt_not_negative"),
    CheckConstraint("lease_expires_at IS NULL OR leased_by IS NOT NULL", name="lease_has_an_owner"),
    # The claim query reads only claimable rows, and a 10 TB import leaves millions of
    # terminal ones behind (12 § queue hygiene) — so the index covers the live set only.
    Index(
        "ix_operation_claimable",
        "priority",
        "next_due_at",
        postgresql_where=text("state IN ('queued', 'running')"),
    ),
    # At most one *queued* operation per key, which is what makes re-detecting pending work
    # converge instead of duplicating it. Deliberately not extended to `running`: a periodic
    # operation queues its own successor while it is still executing, and a key held by the
    # in-flight run would make that impossible. Convergence with running work is a question
    # about work identity rather than about the queue, so `operations.enqueue` answers it.
    Index(
        "uq_operation_idempotency_key",
        "idempotency_key",
        unique=True,
        postgresql_where=text("idempotency_key IS NOT NULL AND state = 'queued'"),
    ),
    Index("ix_operation_kind_state", "kind", "state"),
    Index("ix_operation_subject_type_subject_id", "subject_type", "subject_id"),
)
"""One table for every effectful operation (ADR-0013). A feature that invents its own job
handling is a review-blocker, exactly as ad-hoc file IO is."""


#: Where a workspace's files come from (03 § workspace sources). A column rather than an
#: assumption because `external` (mirrored Google Drive and friends — Q16) is a later
#: source type, not a later redesign.
WORKSPACE_SOURCES = ("local",)

#: Who chose the root directory (ADR-0018): `managed` is ours to shape under `SE_DATA_ROOT`,
#: `adopted` is the user's own directory indexed in place with nothing moved or copied.
WORKSPACE_PLACEMENTS = ("managed", "adopted")

#: A workspace row exists before its directory does — creation records the intent and the
#: `workspace.provision` operation makes it true (ADR-0010). `active` means the root, the
#: control directory and the root folder are all there.
WORKSPACE_STATES = ("provisioning", "active")


workspace = Table(
    "workspace",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    # RESTRICT for the same reason as the event log's actor: a user owns files, so removing
    # one is a data-lifecycle decision (phase 4), never a foreign key's side effect.
    Column(
        "owner_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=False,
    ),
    # `name` as the user typed it, `name_key` what uniqueness and lookups compare
    # (03 § names on disk). Deriving the key in Python is deliberate: case folding is a
    # Unicode operation with a policy behind it (`names.comparison_key`), not `lower()`.
    Column("name", Text, nullable=False),
    Column("name_key", Text, nullable=False),
    Column("source", Text, nullable=False, server_default=text("'local'")),
    Column("placement", Text, nullable=False),
    # Absolute and resolved (`realpath`), so containment checks compare what the kernel
    # would open rather than what a request said.
    Column("root_path", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'provisioning'")),
    # The `fs-check` verdict that admitted this root (ADR-0019). Recorded, not assumed: when
    # a guarantee later turns out not to hold, this says what was probed and what it answered.
    Column("fs_check", JSONB, nullable=False),
    Column("fs_checked_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # One user's workspace names are unique on the comparison key, which is also what keeps
    # their managed directories from colliding — the name is a path segment.
    UniqueConstraint("owner_id", "name_key"),
    # Overlap (one root inside another) needs a query; equality is caught structurally here,
    # which is what makes the check-then-insert race harmless.
    UniqueConstraint("root_path"),
    CheckConstraint(one_of("source", WORKSPACE_SOURCES), name="source_known"),
    CheckConstraint(one_of("placement", WORKSPACE_PLACEMENTS), name="placement_known"),
    CheckConstraint(one_of("state", WORKSPACE_STATES), name="state_known"),
    # `octet_length`, not `length`: the policy is bytes, and a name of 255 characters can be
    # four times that on disk.
    CheckConstraint(f"octet_length(name) BETWEEN 1 AND {MAX_NAME_BYTES}", name="name_length"),
    CheckConstraint(f"octet_length(name_key) BETWEEN 1 AND {MAX_NAME_BYTES}", name="key_length"),
    CheckConstraint("root_path LIKE '/%'", name="root_path_absolute"),
    CheckConstraint(f"octet_length(root_path) <= {MAX_PATH_BYTES}", name="root_path_length"),
    Index("ix_workspace_owner_id_created_at", "owner_id", "created_at"),
)
"""A top-level container of files, owned by exactly one user (02 § workspace)."""


folder = Table(
    "folder",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "workspace_id",
        UUID(as_uuid=True),
        ForeignKey("workspace.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("parent_id", UUID(as_uuid=True), ForeignKey("folder.id", ondelete="CASCADE")),
    Column("name", Text, nullable=False),
    Column("name_key", Text, nullable=False),
    # Redundant with the closure table and worth it: "how deep is this" answers path
    # assembly and the depth limit without a join.
    Column("depth", Integer, nullable=False, server_default=text("0")),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # Sibling uniqueness on the comparison key (F-015/FR-6). Root rows have a NULL parent and
    # never collide here — PostgreSQL treats NULLs as distinct — which the partial index below
    # is for.
    UniqueConstraint("workspace_id", "parent_id", "name_key"),
    Index(
        "uq_folder_workspace_root",
        "workspace_id",
        unique=True,
        postgresql_where=text("parent_id IS NULL"),
    ),
    # The root folder *is* the workspace root directory, so it has no name of its own; every
    # other folder must have one. Structural, because a root that acquired a name would make
    # every derived path wrong.
    # The target of `file`'s composite foreign key. Redundant with the primary key as an
    # index, and load-bearing as a constraint: a foreign key can only reference a uniquely
    # constrained set of columns.
    UniqueConstraint("id", "workspace_id"),
    CheckConstraint("(parent_id IS NULL) = (name = '')", name="root_has_no_name"),
    CheckConstraint("(parent_id IS NULL) = (depth = 0)", name="depth_matches_parent"),
    CheckConstraint(f"octet_length(name) <= {MAX_NAME_BYTES}", name="name_length"),
    Index("ix_folder_parent_id", "parent_id"),
)
"""A directory in a workspace's tree, mirrored 1:1 from disk (F-015). Identified by its
UUID, which survives rename and move — that is what grants and tags attach to."""


folder_closure = Table(
    "folder_closure",
    metadata,
    Column(
        "ancestor_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "descendant_id",
        UUID(as_uuid=True),
        ForeignKey("folder.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("depth", Integer, nullable=False),
    # "Every ancestor of X" — the direction permission evaluation reads.
    Index("ix_folder_closure_descendant_id_depth", "descendant_id", "depth"),
    CheckConstraint("depth >= 0", name="depth_not_negative"),
    CheckConstraint("(ancestor_id = descendant_id) = (depth = 0)", name="self_row_at_depth_zero"),
)
"""Precomputed ancestry (F-015/FR-2, the ADR-0006 pattern): one indexed join answers
"everything under folder F", which is the permission filter's hottest question. Every folder
carries a depth-0 row for itself, so a subtree includes its own root without a special case."""


#: A file's lifecycle (02 § file, [F-014](../../../features/F-014-deletion-and-trash.md)).
#: Phase 1 records `trashed` only so a re-scan can capture a deletion that already happened on
#: disk; deleting *through* the app arrives with the trash surface in phase 4.
FILE_STATES = ("live", "trashed")

#: Who wrote the bytes this version describes (F-007/FR-3). `external` is what a re-scan
#: records when a file changed on disk without the app mediating it.
VERSION_ORIGINS = ("upload", "external")

#: 04 § identification. Assigned by the core from the detected media type before any
#: extractor runs, which is what makes type-scoped listings work on a brand-new file.
MEDIA_CLASSES = ("image", "video", "audio", "document", "archive", "other")

#: Stored beside every hash so a future algorithm is an additive change (02 § FileVersion).
DIGEST_ALGORITHMS = ("sha256",)


file = Table(
    "file",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("workspace_id", UUID(as_uuid=True), nullable=False),
    Column("folder_id", UUID(as_uuid=True), nullable=False),
    Column("name", Text, nullable=False),
    Column("name_key", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'live'")),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # A composite foreign key, not two independent ones: it makes invariant 1 structural —
    # a file's workspace *is* its folder's workspace, so no code path can file a row into
    # another workspace's tree, which would be a permission leak rather than a typo.
    ForeignKeyConstraint(
        ["folder_id", "workspace_id"],
        ["folder.id", "folder.workspace_id"],
        ondelete="CASCADE",
    ),
    UniqueConstraint("folder_id", "name_key"),
    CheckConstraint(one_of("state", FILE_STATES), name="state_known"),
    CheckConstraint(f"octet_length(name) BETWEEN 1 AND {MAX_NAME_BYTES}", name="name_length"),
    Index("ix_file_workspace_id_state", "workspace_id", "state"),
)
"""A logical file, addressed as *(folder, name)* — its path is derived from the folder chain,
never stored (02 § file). The UUID survives rename, move and new versions."""


file_version = Table(
    "file_version",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "file_id", UUID(as_uuid=True), ForeignKey("file.id", ondelete="CASCADE"), nullable=False
    ),
    Column("digest_algorithm", Text, nullable=False, server_default=text("'sha256'")),
    Column("content_hash", Text, nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    Column("media_type", Text, nullable=False),
    Column("media_class", Text, nullable=False),
    Column("origin", Text, nullable=False),
    Column("is_current", Boolean, nullable=False, server_default=text("true")),
    # The mtime the file carried on disk when this version was recorded. The stat-scan
    # compares size and mtime before it hashes anything (ADR-0019), so recording it here is
    # what keeps a scan of 10 TB from being a re-hash of 10 TB.
    Column("modified_at", DateTime(timezone=True), nullable=True),
    _created_at(),
    # Exactly one current version per file, enforced rather than maintained: the alternative
    # — a `current_version_id` on `file` — is a circular foreign key that has to be deferred.
    Index("uq_file_version_current", "file_id", unique=True, postgresql_where=text("is_current")),
    # Reuse of extraction results and duplicate detection both start from "who else has these
    # bytes?" (04 § identification, F-013).
    Index("ix_file_version_content_hash", "content_hash"),
    CheckConstraint("size_bytes >= 0", name="size_not_negative"),
    CheckConstraint(one_of("origin", VERSION_ORIGINS), name="origin_known"),
    CheckConstraint(one_of("media_class", MEDIA_CLASSES), name="media_class_known"),
    CheckConstraint(one_of("digest_algorithm", DIGEST_ALGORITHMS), name="digest_algorithm_known"),
)
"""An immutable snapshot of a file's content, identified by its hash (02 § FileVersion)."""


#: An upload session's life. `open` is the only state a client can act on; the rest are
#: terminal, which is what lets the janitor collect the staged bytes.
UPLOAD_STATES = ("open", "completed", "cancelled", "expired", "failed")


upload_session = Table(
    "upload_session",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "workspace_id",
        UUID(as_uuid=True),
        ForeignKey("workspace.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # Only its creator may drive a session. Not derived from the workspace's owner because
    # grants (phase 4) will let someone else upload into a workspace they do not own.
    Column(
        "created_by",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=False,
    ),
    # Resolved once, at creation: `HEAD` and `PATCH` then need no re-validation, and finalize
    # knows exactly where the bytes are going.
    Column("target_path", Text, nullable=False),
    Column("declared_length", BigInteger, nullable=True),
    Column("declared_hash", Text, nullable=True),
    Column("media_type", Text, nullable=True),
    Column("interop_version", SmallInteger, nullable=True),
    # The offset the client may rely on: bytes are fsync'd before this advances, never after
    # (ADR-0017). Staged bytes beyond it were never acknowledged and are truncated on resume.
    Column("committed_offset", BigInteger, nullable=False, server_default=text("0")),
    Column("state", Text, nullable=False, server_default=text("'open'")),
    Column("file_id", UUID(as_uuid=True), ForeignKey("file.id", ondelete="SET NULL")),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint(one_of("state", UPLOAD_STATES), name="state_known"),
    CheckConstraint("committed_offset >= 0", name="offset_not_negative"),
    CheckConstraint(
        "declared_length IS NULL OR committed_offset <= declared_length",
        name="offset_within_length",
    ),
    CheckConstraint(f"octet_length(target_path) <= {MAX_PATH_BYTES}", name="target_path_length"),
    # The expiry sweep reads only live sessions, which is the whole table's hot query.
    Index(
        "ix_upload_session_expires_at",
        "expires_at",
        postgresql_where=text("state = 'open'"),
    ),
    Index("ix_upload_session_workspace_id_created_at", "workspace_id", "created_at"),
)
"""A resumable upload in progress: the durable row that makes an interrupted multi-gigabyte
upload resumable across restarts (ADR-0017, 03 § uploads). Its staged bytes live in the
workspace's own `.workspace/staging/` area, named after this id, so the janitor can attribute
and collect them."""
