"""Table definitions and the single SQLAlchemy metadata they register on.

There are no ORM model classes by design (ADR-0012): tables are declared here as Core
`Table` objects, and rows map to Pydantic models at the API boundary (`schemas.py`).

Fixing the naming convention *before* the first table exists is deliberate: constraint
and index names become part of migrations the moment a table is created, and renaming
them later is a migration of its own.

Migrations are hand-written rather than autogenerated, so this file and the migration
history could drift. `tests/test_schema_matches_metadata.py` closes that gap by comparing
this metadata against a freshly migrated database.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    Integer,
    MetaData,
    SmallInteger,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import INET, JSONB, UUID

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)

#: Instance-level roles (07-identity-permissions-sharing.md § users).
USER_ROLES = ("admin", "member")

#: Personal-access-token scopes. `read` is least privilege for an agent or a read-only
#: integration; `full` acts as its user. Finer scopes are additive later.
TOKEN_SCOPES = ("read", "full")

#: Who acted (ADR-0007). `system` covers scheduled and startup work with no human behind it.
ACTOR_TYPES = ("user", "extractor", "system")


def _created_at() -> Column[datetime]:
    return Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now())


def one_of(column: str, allowed: tuple[str, ...]) -> str:
    """SQL for "this column holds one of these values".

    Written by hand rather than interpolating a Python tuple: a single-element tuple
    renders as `('x',)`, which is a syntax error, and the migration has to carry the
    identical text.
    """
    values = ", ".join(f"'{value}'" for value in allowed)
    return f"{column} IN ({values})"


app_user = Table(
    "app_user",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    # Stored lower-cased so "Alice@example.com" and "alice@example.com" are one account;
    # the check constraint makes that structural instead of a convention handlers remember.
    Column("email", Text, nullable=False),
    Column("display_name", Text, nullable=False),
    Column("password_hash", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("is_active", Boolean, nullable=False, server_default=text("true")),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("email"),
    CheckConstraint("email = lower(email)", name="email_lowercase"),
    CheckConstraint("length(email) BETWEEN 3 AND 320", name="email_length"),
    CheckConstraint("length(display_name) BETWEEN 1 AND 200", name="display_name_length"),
    CheckConstraint(one_of("role", USER_ROLES), name="role_known"),
)
"""Named `app_user` because `user` is a reserved word in PostgreSQL — quoting it forever
in hand-written SQL (ADR-0012) is a papercut with no upside."""


user_session = Table(
    "user_session",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    ),
    # Only the SHA-256 of the token: a database dump can therefore not be replayed as a
    # set of live sessions (07 § tokens & credentials).
    Column("token_hash", Text, nullable=False),
    Column("user_agent", Text, nullable=True),
    _created_at(),
    Column("last_used_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    # Rolling idle expiry: extended on use, so an active session survives and an abandoned
    # one lapses on its own.
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("token_hash"),
    Index("ix_user_session_user_id_created_at", "user_id", "created_at"),
)


access_token = Table(
    "access_token",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("token_hash", Text, nullable=False),
    Column("scope", Text, nullable=False),
    _created_at(),
    Column("last_used_at", DateTime(timezone=True), nullable=True),
    Column("expires_at", DateTime(timezone=True), nullable=True),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    UniqueConstraint("token_hash"),
    # A name is how its owner recognizes a token in a list, so it has to be unambiguous.
    UniqueConstraint("user_id", "name"),
    CheckConstraint("length(name) BETWEEN 1 AND 100", name="name_length"),
    CheckConstraint(one_of("scope", TOKEN_SCOPES), name="scope_known"),
)


event = Table(
    "event",
    metadata,
    # A gapless-looking integer, not a UUID: the `/events` feed (phase 5) is a cursor over
    # this column. Note for that phase — identity values are assigned before commit, so
    # ids can become visible out of order under concurrency; a cursor feed needs a
    # commit-order-safe watermark rather than `id > $cursor` alone.
    Column("id", BigInteger, Identity(always=True), primary_key=True),
    Column("occurred_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("actor_type", Text, nullable=False),
    # RESTRICT, not CASCADE or SET NULL: the audit trail outlives everything else
    # (F-011/FR-2), so removing a user is a decision a later phase has to make
    # deliberately rather than a side effect of a foreign key.
    Column(
        "actor_user_id",
        UUID(as_uuid=True),
        ForeignKey("app_user.id", ondelete="RESTRICT"),
        nullable=True,
    ),
    Column("action", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("resource_id", UUID(as_uuid=True), nullable=True),
    # Self-contained by design (F-011/FR-9): names and paths as they were at action time,
    # so history stays readable after the resource is purged.
    Column("details", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("request_id", Text, nullable=True),
    Column("client_ip", INET, nullable=True),
    CheckConstraint(one_of("actor_type", ACTOR_TYPES), name="actor_type_known"),
    CheckConstraint(
        "actor_type <> 'user' OR actor_user_id IS NOT NULL",
        name="user_actor_identified",
    ),
    Index("ix_event_occurred_at_id", "occurred_at", "id"),
    Index("ix_event_resource_type_resource_id_id", "resource_type", "resource_id", "id"),
    Index("ix_event_actor_user_id_id", "actor_user_id", "id"),
    # Serves the credential-abuse queries, which count recent events of one action
    # (07 § abuse protection).
    Index("ix_event_action_occurred_at", "action", "occurred_at"),
)
"""The append-only event log (ADR-0007). Writes ride the transaction of the change they
describe; `UPDATE` is refused by a database trigger, so immutability does not depend on
every future code path remembering it."""


#: The operation state machine (12-reliability.md § operation records). `queued` doubles as
#: "waiting for a retry" — a retryable failure returns to it with a later `next_due_at` — so
#: the only non-terminal states are `queued` and `running`.
OPERATION_STATES = (
    "queued",
    "running",
    "succeeded",
    "failed",
    "dead_letter",
    "cancelled",
    "superseded",
)

#: Nothing claims these again, and their idempotency key becomes free for reuse.
TERMINAL_OPERATION_STATES = ("succeeded", "failed", "dead_letter", "cancelled", "superseded")

#: Priority classes from 04-ingestion-pipeline.md § prioritization: 0 = interactive,
#: 1 = presence, 2 = searchability, 3 = heavy derived, 4 = reprocessing. Lower runs first.
MIN_PRIORITY, MAX_PRIORITY = 0, 4


operation = Table(
    "operation",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("kind", Text, nullable=False),
    Column("state", Text, nullable=False, server_default=text("'queued'")),
    Column("priority", SmallInteger, nullable=False, server_default=text("2")),
    # Counted on *claim*, not on failure: a job that OOM-kills its worker never reports an
    # error, and counting here is what dead-letters it anyway (12 § leases & fencing).
    Column("attempt", Integer, nullable=False, server_default=text("0")),
    Column("max_attempts", Integer, nullable=False),
    # The durable schedule. Retry backoff, periodic work and "run now" are all this column;
    # in-memory timers are forbidden (ADR-0010 rule 1).
    Column("next_due_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("leased_by", Text, nullable=True),
    Column("lease_expires_at", DateTime(timezone=True), nullable=True),
    # The cancellation channel: a worker learns of it from its heartbeat response rather
    # than from a signal, so cancellation survives a restart like everything else.
    Column("cancel_requested", Boolean, nullable=False, server_default=text("false")),
    Column("idempotency_key", Text, nullable=True),
    Column("payload", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("result", JSONB, nullable=True),
    Column("error", Text, nullable=True),
    # What the operation is about, so per-file and per-workspace status stays answerable
    # (04 § status & observability) without one table per operation kind.
    Column("subject_type", Text, nullable=True),
    Column("subject_id", UUID(as_uuid=True), nullable=True),
    _created_at(),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    CheckConstraint(one_of("state", OPERATION_STATES), name="state_known"),
    CheckConstraint(
        f"priority BETWEEN {MIN_PRIORITY} AND {MAX_PRIORITY}", name="priority_in_range"
    ),
    CheckConstraint("max_attempts > 0", name="max_attempts_positive"),
    CheckConstraint("attempt >= 0", name="attempt_not_negative"),
    CheckConstraint("lease_expires_at IS NULL OR leased_by IS NOT NULL", name="lease_has_an_owner"),
    # The claim query reads only claimable rows, and a 10 TB import leaves millions of
    # terminal ones behind (12 § queue hygiene) — so the index covers the live set only.
    Index(
        "ix_operation_claimable",
        "priority",
        "next_due_at",
        postgresql_where=text("state IN ('queued', 'running')"),
    ),
    # At most one *queued* operation per key, which is what makes re-detecting pending work
    # converge instead of duplicating it. Deliberately not extended to `running`: a periodic
    # operation queues its own successor while it is still executing, and a key held by the
    # in-flight run would make that impossible. Convergence with running work is a question
    # about work identity rather than about the queue, so `operations.enqueue` answers it.
    Index(
        "uq_operation_idempotency_key",
        "idempotency_key",
        unique=True,
        postgresql_where=text("idempotency_key IS NOT NULL AND state = 'queued'"),
    ),
    Index("ix_operation_kind_state", "kind", "state"),
    Index("ix_operation_subject_type_subject_id", "subject_type", "subject_id"),
)
"""One table for every effectful operation (ADR-0013). A feature that invents its own job
handling is a review-blocker, exactly as ad-hoc file IO is."""
