"""Identity and the event log.

Accounts, sessions and personal access tokens (07-identity-permissions-sharing.md), plus
the append-only event log every mutation rides from here on (ADR-0007). They arrive in one
migration because they are one thing: the first mutation this system can perform is
creating a user, and it must already be logged.

Written by hand, not autogenerated — the DDL is reviewable this way, and
`test_schema_matches_metadata` proves it agrees with `tables.py`.

Check constraints carry their *short* names here: the metadata naming convention
interpolates `%(constraint_name)s`, so a fully qualified name would come out doubled.

Revision ID: 0002_identity_and_events
Revises: 0001_baseline
Create Date: 2026-08-20
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from store_everything.tables import ACTOR_TYPES, TOKEN_SCOPES, USER_ROLES, one_of

revision: str = "0002_identity_and_events"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Refusing `UPDATE` in the database means immutability does not rely on every future code
#: path remembering it (F-011/FR-2). `DELETE` stays possible on purpose: retention pruning
#: is the one sanctioned removal (F-011/FR-8), and it is itself audited.
_IMMUTABILITY_FUNCTION = """
CREATE OR REPLACE FUNCTION event_is_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'event rows are immutable (ADR-0007); no UPDATE is permitted';
END;
$$ LANGUAGE plpgsql
"""


def upgrade() -> None:
    op.create_table(
        "app_user",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_app_user"),
        sa.UniqueConstraint("email", name="uq_app_user_email"),
        sa.CheckConstraint("email = lower(email)", name="email_lowercase"),
        sa.CheckConstraint("length(email) BETWEEN 3 AND 320", name="email_length"),
        sa.CheckConstraint("length(display_name) BETWEEN 1 AND 200", name="display_name_length"),
        sa.CheckConstraint(one_of("role", USER_ROLES), name="role_known"),
    )

    op.create_table(
        "user_session",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "last_used_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_user_session"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name="fk_user_session_user_id_app_user",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_hash", name="uq_user_session_token_hash"),
    )
    op.create_index("ix_user_session_user_id_created_at", "user_session", ["user_id", "created_at"])

    op.create_table(
        "access_token",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_access_token"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name="fk_access_token_user_id_app_user",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_hash", name="uq_access_token_token_hash"),
        sa.UniqueConstraint("user_id", "name", name="uq_access_token_user_id_name"),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 100", name="name_length"),
        sa.CheckConstraint(one_of("scope", TOKEN_SCOPES), name="scope_known"),
    )

    op.create_table(
        "event",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("client_ip", postgresql.INET(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_event"),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["app_user.id"],
            name="fk_event_actor_user_id_app_user",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(one_of("actor_type", ACTOR_TYPES), name="actor_type_known"),
        sa.CheckConstraint(
            "actor_type <> 'user' OR actor_user_id IS NOT NULL",
            name="user_actor_identified",
        ),
    )
    op.create_index("ix_event_occurred_at_id", "event", ["occurred_at", "id"])
    op.create_index(
        "ix_event_resource_type_resource_id_id",
        "event",
        ["resource_type", "resource_id", "id"],
    )
    op.create_index("ix_event_actor_user_id_id", "event", ["actor_user_id", "id"])
    op.create_index("ix_event_action_occurred_at", "event", ["action", "occurred_at"])

    op.execute(_IMMUTABILITY_FUNCTION)
    op.execute(
        "CREATE TRIGGER event_no_update BEFORE UPDATE ON event "
        "FOR EACH STATEMENT EXECUTE FUNCTION event_is_append_only()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS event_no_update ON event")
    op.execute("DROP FUNCTION IF EXISTS event_is_append_only()")

    op.drop_index("ix_event_action_occurred_at", table_name="event")
    op.drop_index("ix_event_actor_user_id_id", table_name="event")
    op.drop_index("ix_event_resource_type_resource_id_id", table_name="event")
    op.drop_index("ix_event_occurred_at_id", table_name="event")
    op.drop_table("event")

    op.drop_table("access_token")

    op.drop_index("ix_user_session_user_id_created_at", table_name="user_session")
    op.drop_table("user_session")

    op.drop_table("app_user")
